## 목표 변수
- 주변 음식점 수
- 주변 프렌차이즈 카페 수
- 주변 스타벅스 카페 수
- 이전 달 새로 생긴 카페 수
- 별식/퓨전요리업종 매출액
- 양식업종 점포수
- 요가/단전/마사지업종 매출액
- 인테리어/소품업종 이용건수
- 주거고객 학문/교육업종 이용건수

```
No	출력명	출력설명
공통	list_total_count	총 데이터 건수 (정상조회 시 출력됨)
공통	RESULT.CODE	요청결과 코드 (하단 메세지설명 참고)
공통	RESULT.MESSAGE	요청결과 메시지 (하단 메세지설명 참고)
1	STDR_YY_CD	기준_년_코드
2	STDR_QU_CD	기준_분기_코드
3	TRDAR_SE_CD	상권_구분_코드
4	TRDAR_SE_CD_NM	상권_구분_코드_명
5	TRDAR_CD	상권_코드
6	TRDAR_CD_NM	상권_코드_명
7	SVC_INDUTY_CD	서비스_업종_코드
8	SVC_INDUTY_CD_NM	서비스_업종_코드_명
9	STOR_CO	점포_수
10	SIMILR_INDUTY_STOR_CO	유사_업종_점포_수
11	OPBIZ_RT	개업_율
12	OPBIZ_STOR_CO	개업_점포_수
13	CLSBIZ_RT	폐업_률
14	CLSBIZ_STOR_CO	폐업_점포_수
15	FRC_STOR_CO	프랜차이즈_점포_수
```

In [1]:

import xmltodict

import pandas as pd
import urllib.request
import json

from urllib.request import urlopen 
from bs4 import BeautifulSoup

import my_api

In [2]:
my_key = my_api.get_public_api()

In [32]:
url = "http://openapi.seoul.go.kr:8088/"+ my_key +"/xml/VwsmTrdhlStorQq/181792/181800/2021/CS100010"
request = urllib.request.Request(url)
response = urllib.request.urlopen(request)
cc = xmltodict.parse(response.read().decode('utf-8')) # return collections.OrderedDict
dd = json.loads(json.dumps(cc)) # return dict
dd

{'VwsmTrdhlStorQq': {'list_total_count': '181794',
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'STDR_YY_CD': '2021',
    'STDR_QU_CD': '2',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1001010',
    'TRDAR_CD_NM': '풍성로37가길',
    'SVC_INDUTY_CD': 'CS300041',
    'SVC_INDUTY_CD_NM': '예술품',
    'STOR_CO': '1',
    'SIMILR_INDUTY_STOR_CO': '1',
    'OPBIZ_RT': '0',
    'OPBIZ_STOR_CO': '0',
    'CLSBIZ_RT': '0',
    'CLSBIZ_STOR_CO': '0',
    'FRC_STOR_CO': '0'},
   {'STDR_YY_CD': '2021',
    'STDR_QU_CD': '2',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1001010',
    'TRDAR_CD_NM': '풍성로37가길',
    'SVC_INDUTY_CD': 'CS300042',
    'SVC_INDUTY_CD_NM': '주유소',
    'STOR_CO': '2',
    'SIMILR_INDUTY_STOR_CO': '2',
    'OPBIZ_RT': '0',
    'OPBIZ_STOR_CO': '0',
    'CLSBIZ_RT': '0',
    'CLSBIZ_STOR_CO': '0',
    'FRC_STOR_CO': '0'},
   {'STDR_YY_CD': '2021',
    'STDR_QU_CD': '2',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1001010',
    'TRDAR_CD_NM': '풍성로37가길',
    'SVC_INDUTY_CD': 'CS300043',
    'SVC_INDUTY_CD_NM': '전자상거래업',
    'STOR_CO': '33',
    'SIMILR_INDUTY_STOR_CO': '33',
    'OPBIZ_RT': '0',
    'OPBIZ_STOR_CO': '0',
    'CLSBIZ_RT': '0',
    'CLSBIZ_STOR_CO': '0',
    'FRC_STOR_CO': '0'}]}}

In [33]:
def get_SangGwan(api_key, start, end, year, svc_induty_cd=''):
    url = f"http://openapi.seoul.go.kr:8088/{api_key}/xml/VwsmTrdhlStorQq/{start}/{end}/{year}/{svc_induty_cd}"
    request = urllib.request.Request(url)
    response = urllib.request.urlopen(request)
    cc = xmltodict.parse(response.read().decode('utf-8')) # return collections.OrderedDict
    dd = json.loads(json.dumps(cc)) # return dict
    return dd['VwsmTrdhlStorQq']

def get_all_SangGwan(api_key, year, max_cnt=None, svc_induty_cd=''):
    if max_cnt == None:
        total_cnt = int(get_SangGwan(api_key, 1, 1, year).get('list_total_count'))
        print(f'총 {total_cnt} 존재')
    else:
        total_cnt = max_cnt
        print(f'총 {total_cnt}건에 대해 api 호출')
    ls = []
    for start in range(1, total_cnt, 1000):
        get_item = get_SangGwan(api_key, start, start+999, year, svc_induty_cd)
        ls.extend(get_item['row'])
        print(f'{start} ~ {start+999} 추출 완료')
    print("끝!!!")
    return pd.DataFrame(ls)

In [34]:
# 2014년부터 데이터가 있는듯

df = get_all_SangGwan(my_key, 2014, 1000)
df

총 100건에 대해 api 호출
1 ~ 1000 추출 완료
끝!!!

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,STOR_CO,SIMILR_INDUTY_STOR_CO,OPBIZ_RT,OPBIZ_STOR_CO,CLSBIZ_RT,CLSBIZ_STOR_CO,FRC_STOR_CO
0,2014,1,A,골목상권,1000001,계동길,CS100001,한식음식점,117,122,5,6,5,6,5
1,2014,1,A,골목상권,1000001,계동길,CS100002,중식음식점,6,6,0,0,17,1,0
2,2014,1,A,골목상권,1000001,계동길,CS100003,일식음식점,5,7,0,0,0,0,2
3,2014,1,A,골목상권,1000001,계동길,CS100004,양식음식점,30,34,3,1,0,0,4
4,2014,1,A,골목상권,1000001,계동길,CS100005,제과점,6,12,0,0,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2014,1,A,골목상권,1000013,율곡로10길,CS200012,법무사사무소,4,4,0,0,0,0,0
996,2014,1,A,골목상권,1000013,율곡로10길,CS200013,기타법무서비스,3,3,0,0,0,0,0
997,2014,1,A,골목상권,1000013,율곡로10길,CS200014,회계사사무소,5,5,0,0,0,0,0
998,2014,1,A,골목상권,1000013,율곡로10길,CS200015,세무사사무소,72,72,3,2,0,0,0
999,2014,1,A,골목상권,1000013,율곡로10길,CS200016,당구장,3,3,0,0,33,1,0

In [35]:
len(df['TRDAR_CD_NM'].unique())

13

In [36]:
df.columns

Index(['STDR_YY_CD', 'STDR_QU_CD', 'TRDAR_SE_CD', 'TRDAR_SE_CD_NM', 'TRDAR_CD',
       'TRDAR_CD_NM', 'SVC_INDUTY_CD', 'SVC_INDUTY_CD_NM', 'STOR_CO',
       'SIMILR_INDUTY_STOR_CO', 'OPBIZ_RT', 'OPBIZ_STOR_CO', 'CLSBIZ_RT',
       'CLSBIZ_STOR_CO', 'FRC_STOR_CO'],
      dtype='object')

In [37]:
df['SVC_INDUTY_CD_NM'].unique()

array(['한식음식점', '중식음식점', '일식음식점', '양식음식점', '제과점', '패스트푸드점', '치킨전문점',
       '분식전문점', '호프-간이주점', '커피-음료', '일반교습학원', '외국어학원', '예술학원', '치과의원',
       '스포츠 강습', '일반의원', '한의원', '숙박업', '변호사사무소', 'PC방', '법무사사무소',
       '기타법무서비스', '스포츠클럽', '자동차수리·세차', '당구장', '볼링장', '기타오락장', '자동차수리',
       '모터사이클수리', '미용실', '세탁소', '가전제품수리', '부동산중개업', '여관', '게스트하우스', '노래방',
       '독서실', '사진관', '통번역서비스', '건축물청소', '여행사', '비디오/서적임대', '슈퍼마켓', '편의점',
       '컴퓨터및주변장치판매', '핸드폰', '주류도매', '미곡판매', '육류판매', '패션용품', '청과상', '반찬가게',
       '일반의류', '한복점', '유아의류', '신발', '가방', '안경', '시계및귀금속', '의약품', '서적',
       '문구', '화장품', '미용재료', '운동/경기용품', '완구', '섬유제품', '화초', '가구', '가전제품',
       '철물점', '악기', '인테리어', '조명용품', '예술품', '주유소', '전자상거래업', '컴퓨터학원',
       '동물병원', '회계사사무소', '세무사사무소', '골프연습장', '전자게임장', '복권방', '통신기기수리',
       '네일숍', '피부관리실', '고시원', 'DVD방', '의류임대', '수산물판매', '오락·운동', '의료기기',
       '자전거 및 기타운송장비', '애완동물', '중고가구', '중고차판매', '자동차부품', '모터사이클및부품',
       '재생용품 판매점', '변리사사무소', '자동차미용', '녹음실', '가정용품임대', '세탁소(가정)', '두발미용업',
       '주방·가정용품', '식료품'], dtype=object)

In [38]:
df['TRDAR_SE_CD_NM'].unique()

array(['골목상권'], dtype=object)

In [39]:
df[df['SVC_INDUTY_CD_NM']=='커피-음료']

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,STOR_CO,SIMILR_INDUTY_STOR_CO,OPBIZ_RT,OPBIZ_STOR_CO,CLSBIZ_RT,CLSBIZ_STOR_CO,FRC_STOR_CO
9,2014,1,A,골목상권,1000001,계동길,CS100010,커피-음료,59,67,3,2,6,4,8
89,2014,1,A,골목상권,1000002,난계로27길,CS100010,커피-음료,31,41,7,3,0,0,10
186,2014,1,A,골목상권,1000003,돈화문로11가길,CS100010,커피-음료,94,106,3,3,6,6,12
283,2014,1,A,골목상권,1000004,명륜길,CS100010,커피-음료,14,16,13,2,0,0,2
357,2014,1,A,골목상권,1000005,백석동길,CS100010,커피-음료,19,19,5,1,0,0,0
428,2014,1,A,골목상권,1000006,북촌로11길,CS100010,커피-음료,82,91,8,7,7,6,9
511,2014,1,A,골목상권,1000007,북촌로5길,CS100010,커피-음료,74,87,6,5,7,6,13
593,2014,1,A,골목상권,1000008,북촌로5나길,CS100010,커피-음료,58,64,8,5,8,5,6
659,2014,1,A,골목상권,1000009,삼청로5길,CS100010,커피-음료,63,70,9,6,9,6,7
725,2014,1,A,골목상권,1000010,성균관로5길,CS100010,커피-음료,68,82,7,6,11,9,14
811,2014,1,A,골목상권,1000011,숭인동길,CS100010,커피-음료,36,45,7,3,0,0,9
907,2014,1,A,골목상권,1000012,옥인길,CS100010,커피-음료,35,36,22,8,3,1,1
983,2014,1,A,골목상권,1000013,율곡로10길,CS100010,커피-음료,42,45,4,2,4,2,3

In [41]:
df_ls = []
for year in range(2014, 2022):
    df_year = get_all_SangGwan(my_key, year)
    df_ls.append(df_year)

총 372068 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
끝!!!
총 373391 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료

11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
373001 ~ 374000 추출 완료
끝!!!
총 374770 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료

20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
373001 ~ 374000 추출 완료
374001 ~ 375000 추출 완료
끝!!!
총 376102 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료

28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
373001 ~ 374000 추출 완료
374001 ~ 375000 추출 완료
375001 ~ 376000 추출 완료
376001 ~ 377000 추출 완료
끝!!!
총 376923 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료

34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
373001 ~ 374000 추출 완료
374001 ~ 375000 추출 완료
375001 ~ 376000 추출 완료
376001 ~ 377000 추출 완료
끝!!!
총 373622 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료

40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
364001 ~ 365000 추출 완료
365001 ~ 366000 추출 완료
366001 ~ 367000 추출 완료
367001 ~ 368000 추출 완료
368001 ~ 369000 추출 완료
369001 ~ 370000 추출 완료
370001 ~ 371000 추출 완료
371001 ~ 372000 추출 완료
372001 ~ 373000 추출 완료
373001 ~ 374000 추출 완료
끝!!!
총 363243 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료

49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
182001 ~ 183000 추출 완료
183001 ~ 184000 추출 완료
184001 ~ 185000 추출 완료
185001 ~ 186000 추출 완료
186001 ~ 187000 추출 완료
187001 ~ 188000 추출 완료
188001 ~ 189000 추출 완료
189001 ~ 190000 추출 완료
190001 ~ 191000 추출 완료
191001 ~ 192000 추출 완료
192001 ~ 193000 추출 완료
193001 ~ 194000 추출 완료
194001 ~ 195000 추출 완료
195001 ~ 196000 추출 완료
196001 ~ 197000 추출 완료
197001 ~ 198000 추출 완료
198001 ~ 199000 추출 완료
199001 ~ 200000 추출 완료
200001 ~ 201000 추출 완료
201001 ~ 202000 추출 완료
202001 ~ 203000 추출 완료
203001 ~ 204000 추출 완료
204001 ~ 205000 추출 완료
205001 ~ 206000 추출 완료
206001 ~ 207000 추출 완료
207001 ~ 208000 추출 완료
208001 ~ 209000 추출 완료
209001 ~ 210000 추출 완료
210001 ~ 211000 추출 완료
211001 ~ 212000 추출 완료
212001 ~ 213000 추출 완료
213001 ~ 214000 추출 완료
214001 ~ 215000 추출 완료
215001 ~ 216000 추출 완료
216001 ~ 217000 추출 완료
217001 ~ 218000 추출 완료
218001 ~ 219000 추출 완료
219001 ~ 220000 추출 완료
220001 ~ 221000 추출 완료
221001 ~ 222000 추출 완료
222001 ~ 223000 추출 완료
223001 ~ 224000 추출 완료
224001 ~ 225000 추출 완료
225001 ~ 226000 추출 완료
226001 ~ 227000 추출 완료
227001 ~ 228000 추출 완료
228001 ~ 229000 추출 완료
229001 ~ 230000 추출 완료
230001 ~ 231000 추출 완료
231001 ~ 232000 추출 완료
232001 ~ 233000 추출 완료
233001 ~ 234000 추출 완료
234001 ~ 235000 추출 완료
235001 ~ 236000 추출 완료
236001 ~ 237000 추출 완료
237001 ~ 238000 추출 완료
238001 ~ 239000 추출 완료
239001 ~ 240000 추출 완료
240001 ~ 241000 추출 완료
241001 ~ 242000 추출 완료
242001 ~ 243000 추출 완료
243001 ~ 244000 추출 완료
244001 ~ 245000 추출 완료
245001 ~ 246000 추출 완료
246001 ~ 247000 추출 완료
247001 ~ 248000 추출 완료
248001 ~ 249000 추출 완료
249001 ~ 250000 추출 완료
250001 ~ 251000 추출 완료
251001 ~ 252000 추출 완료
252001 ~ 253000 추출 완료
253001 ~ 254000 추출 완료
254001 ~ 255000 추출 완료
255001 ~ 256000 추출 완료
256001 ~ 257000 추출 완료
257001 ~ 258000 추출 완료
258001 ~ 259000 추출 완료
259001 ~ 260000 추출 완료
260001 ~ 261000 추출 완료
261001 ~ 262000 추출 완료
262001 ~ 263000 추출 완료
263001 ~ 264000 추출 완료
264001 ~ 265000 추출 완료
265001 ~ 266000 추출 완료
266001 ~ 267000 추출 완료
267001 ~ 268000 추출 완료
268001 ~ 269000 추출 완료
269001 ~ 270000 추출 완료
270001 ~ 271000 추출 완료
271001 ~ 272000 추출 완료
272001 ~ 273000 추출 완료
273001 ~ 274000 추출 완료
274001 ~ 275000 추출 완료
275001 ~ 276000 추출 완료
276001 ~ 277000 추출 완료
277001 ~ 278000 추출 완료
278001 ~ 279000 추출 완료
279001 ~ 280000 추출 완료
280001 ~ 281000 추출 완료
281001 ~ 282000 추출 완료
282001 ~ 283000 추출 완료
283001 ~ 284000 추출 완료
284001 ~ 285000 추출 완료
285001 ~ 286000 추출 완료
286001 ~ 287000 추출 완료
287001 ~ 288000 추출 완료
288001 ~ 289000 추출 완료
289001 ~ 290000 추출 완료
290001 ~ 291000 추출 완료
291001 ~ 292000 추출 완료
292001 ~ 293000 추출 완료
293001 ~ 294000 추출 완료
294001 ~ 295000 추출 완료
295001 ~ 296000 추출 완료
296001 ~ 297000 추출 완료
297001 ~ 298000 추출 완료
298001 ~ 299000 추출 완료
299001 ~ 300000 추출 완료
300001 ~ 301000 추출 완료
301001 ~ 302000 추출 완료
302001 ~ 303000 추출 완료
303001 ~ 304000 추출 완료
304001 ~ 305000 추출 완료
305001 ~ 306000 추출 완료
306001 ~ 307000 추출 완료
307001 ~ 308000 추출 완료
308001 ~ 309000 추출 완료
309001 ~ 310000 추출 완료
310001 ~ 311000 추출 완료
311001 ~ 312000 추출 완료
312001 ~ 313000 추출 완료
313001 ~ 314000 추출 완료
314001 ~ 315000 추출 완료
315001 ~ 316000 추출 완료
316001 ~ 317000 추출 완료
317001 ~ 318000 추출 완료
318001 ~ 319000 추출 완료
319001 ~ 320000 추출 완료
320001 ~ 321000 추출 완료
321001 ~ 322000 추출 완료
322001 ~ 323000 추출 완료
323001 ~ 324000 추출 완료
324001 ~ 325000 추출 완료
325001 ~ 326000 추출 완료
326001 ~ 327000 추출 완료
327001 ~ 328000 추출 완료
328001 ~ 329000 추출 완료
329001 ~ 330000 추출 완료
330001 ~ 331000 추출 완료
331001 ~ 332000 추출 완료
332001 ~ 333000 추출 완료
333001 ~ 334000 추출 완료
334001 ~ 335000 추출 완료
335001 ~ 336000 추출 완료
336001 ~ 337000 추출 완료
337001 ~ 338000 추출 완료
338001 ~ 339000 추출 완료
339001 ~ 340000 추출 완료
340001 ~ 341000 추출 완료
341001 ~ 342000 추출 완료
342001 ~ 343000 추출 완료
343001 ~ 344000 추출 완료
344001 ~ 345000 추출 완료
345001 ~ 346000 추출 완료
346001 ~ 347000 추출 완료
347001 ~ 348000 추출 완료
348001 ~ 349000 추출 완료
349001 ~ 350000 추출 완료
350001 ~ 351000 추출 완료
351001 ~ 352000 추출 완료
352001 ~ 353000 추출 완료
353001 ~ 354000 추출 완료
354001 ~ 355000 추출 완료
355001 ~ 356000 추출 완료
356001 ~ 357000 추출 완료
357001 ~ 358000 추출 완료
358001 ~ 359000 추출 완료
359001 ~ 360000 추출 완료
360001 ~ 361000 추출 완료
361001 ~ 362000 추출 완료
362001 ~ 363000 추출 완료
363001 ~ 364000 추출 완료
끝!!!
총 181794 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료

69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
178001 ~ 179000 추출 완료
179001 ~ 180000 추출 완료
180001 ~ 181000 추출 완료
181001 ~ 182000 추출 완료
끝!!!

In [42]:
df_all = pd.concat( df_ls)
df_all

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,STOR_CO,SIMILR_INDUTY_STOR_CO,OPBIZ_RT,OPBIZ_STOR_CO,CLSBIZ_RT,CLSBIZ_STOR_CO,FRC_STOR_CO
0,2014,1,A,골목상권,1000001,계동길,CS100001,한식음식점,117,122,5,6,5,6,5
1,2014,1,A,골목상권,1000001,계동길,CS100002,중식음식점,6,6,0,0,17,1,0
2,2014,1,A,골목상권,1000001,계동길,CS100003,일식음식점,5,7,0,0,0,0,2
3,2014,1,A,골목상권,1000001,계동길,CS100004,양식음식점,30,34,3,1,0,0,4
4,2014,1,A,골목상권,1000001,계동길,CS100005,제과점,6,12,0,0,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181789,2021,2,A,골목상권,1001010,풍성로37가길,CS300039,모터사이클및부품,3,3,0,0,0,0,0
181790,2021,2,A,골목상권,1001010,풍성로37가길,CS300040,재생용품 판매점,4,4,0,0,0,0,0
181791,2021,2,A,골목상권,1001010,풍성로37가길,CS300041,예술품,1,1,0,0,0,0,0
181792,2021,2,A,골목상권,1001010,풍성로37가길,CS300042,주유소,2,2,0,0,0,0,0
181793,2021,2,A,골목상권,1001010,풍성로37가길,CS300043,전자상거래업,33,33,0,0,0,0,0

In [43]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2791913 entries, 0 to 181793
Data columns (total 15 columns):
 #   Column                 Dtype
---  ------                 -----
 0   STDR_YY_CD             object
 1   STDR_QU_CD             object
 2   TRDAR_SE_CD            object
 3   TRDAR_SE_CD_NM         object
 4   TRDAR_CD               object
 5   TRDAR_CD_NM            object
 6   SVC_INDUTY_CD          object
 7   SVC_INDUTY_CD_NM       object
 8   STOR_CO                object
 9   SIMILR_INDUTY_STOR_CO  object
 10  OPBIZ_RT               object
 11  OPBIZ_STOR_CO          object
 12  CLSBIZ_RT              object
 13  CLSBIZ_STOR_CO         object
 14  FRC_STOR_CO            object
dtypes: object(15)
memory usage: 340.8+ MB

In [44]:
# df_all.to_csv('sanggwan_raw.csv')

In [8]:
df_all = pd.read_csv("sanggwan_raw.csv", index_col=0)

In [9]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2791913 entries, 0 to 181793
Data columns (total 15 columns):
 #   Column                 Dtype
---  ------                 -----
 0   STDR_YY_CD             int64
 1   STDR_QU_CD             int64
 2   TRDAR_SE_CD            object
 3   TRDAR_SE_CD_NM         object
 4   TRDAR_CD               int64
 5   TRDAR_CD_NM            object
 6   SVC_INDUTY_CD          object
 7   SVC_INDUTY_CD_NM       object
 8   STOR_CO                int64
 9   SIMILR_INDUTY_STOR_CO  int64
 10  OPBIZ_RT               int64
 11  OPBIZ_STOR_CO          int64
 12  CLSBIZ_RT              int64
 13  CLSBIZ_STOR_CO         int64
 14  FRC_STOR_CO            int64
dtypes: int64(10), object(5)
memory usage: 340.8+ MB

In [18]:
df2 = df_all.copy()
df2['y_q_TRDAR_CD_NM'] = df2['STDR_YY_CD'].astype(str) + "_" + df2['STDR_QU_CD'].astype(str) + "_" +df2['TRDAR_CD_NM']
df2.set_index('y_q_TRDAR_CD_NM', inplace=True)
df2.head()

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,STOR_CO,SIMILR_INDUTY_STOR_CO,OPBIZ_RT,OPBIZ_STOR_CO,CLSBIZ_RT,CLSBIZ_STOR_CO,FRC_STOR_CO
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100001,한식음식점,117,122,5,6,5,6,5
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100002,중식음식점,6,6,0,0,17,1,0
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100003,일식음식점,5,7,0,0,0,0,2
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100004,양식음식점,30,34,3,1,0,0,4
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100005,제과점,6,12,0,0,0,0,6

In [20]:
food_ls = ['한식음식점', '중식음식점', '일식음식점', '양식음식점', '패스트푸드점', '치킨전문점']

In [21]:
def get_store_num(df, food):
    return df[df["SVC_INDUTY_CD_NM"]==food]['SIMILR_INDUTY_STOR_CO'].rename(food, inplace=True)

def get_all_store_num(df, food_ls):
    result_df = pd.DataFrame(index=df.index.unique())
    for food in food_ls:
        store_num = get_store_num(df, food)
        result_df[food + '_개수'] = store_num
    return result_df

In [26]:
df3 = get_all_store_num(df2, food_ls)
df3

                 한식음식점_개수  중식음식점_개수  일식음식점_개수  양식음식점_개수  패스트푸드점_개수  치킨전문점_개수
y_q_TRDAR_CD_NM
2014_1_계동길            122         6       7.0      34.0        8.0         7
2014_1_난계로27길         223        12      12.0       5.0        7.0        10
2014_1_돈화문로11가길       537        18      19.0      36.0       14.0        10
2014_1_명륜길             42         2       1.0       6.0        5.0         8
2014_1_백석동길            16         0       2.0       6.0        2.0         1
...                   ...       ...       ...       ...        ...       ...
2021_2_천호대로197길        57         5       5.0       3.0        5.0         9
2021_2_천호대로219길        85         9       7.0       6.0        5.0        13
2021_2_천호옛14길         189        21      23.0      25.0       19.0        21
2021_2_천호옛길           184        16      23.0      13.0       15.0        23
2021_2_풍성로37가길        134        13      20.0       8.0       12.0        25

[30300 rows x 6 columns]

In [27]:
df_coffee = df2[df2['SVC_INDUTY_CD_NM']=="커피-음료"]
df_coffee

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,STOR_CO,SIMILR_INDUTY_STOR_CO,OPBIZ_RT,OPBIZ_STOR_CO,CLSBIZ_RT,CLSBIZ_STOR_CO,FRC_STOR_CO
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,
2014_1_계동길,2014,1,A,골목상권,1000001,계동길,CS100010,커피-음료,59,67,3,2,6,4,8
2014_1_난계로27길,2014,1,A,골목상권,1000002,난계로27길,CS100010,커피-음료,31,41,7,3,0,0,10
2014_1_돈화문로11가길,2014,1,A,골목상권,1000003,돈화문로11가길,CS100010,커피-음료,94,106,3,3,6,6,12
2014_1_명륜길,2014,1,A,골목상권,1000004,명륜길,CS100010,커피-음료,14,16,13,2,0,0,2
2014_1_백석동길,2014,1,A,골목상권,1000005,백석동길,CS100010,커피-음료,19,19,5,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021_2_천호대로197길,2021,2,A,골목상권,1001006,천호대로197길,CS100010,커피-음료,17,21,19,4,0,0,4
2021_2_천호대로219길,2021,2,A,골목상권,1001007,천호대로219길,CS100010,커피-음료,18,22,9,2,5,1,4
2021_2_천호옛14길,2021,2,A,골목상권,1001008,천호옛14길,CS100010,커피-음료,45,67,5,3,2,1,22
2021_2_천호옛길,2021,2,A,골목상권,1001009,천호옛길,CS100010,커피-음료,46,56,4,2,7,4,10
2021_2_풍성로37가길,2021,2,A,골목상권,1001010,풍성로37가길,CS100010,커피-음료,42,45,2,1,2,1,3

In [28]:
# FRC_STOR_CO, CLSBIZ_STOR_CO, OPBIZ_STOR_CO    프랜차이즈_점포_수, 폐업_점포_수, 개업_점포_수
df_coffee = df_coffee[['FRC_STOR_CO', 'CLSBIZ_STOR_CO', 'OPBIZ_STOR_CO']]
df_coffee.rename(columns={"FRC_STOR_CO":"프랜차이즈_점포_수", 
                          "CLSBIZ_STOR_CO":"폐업_점포_수", 
                          "OPBIZ_STOR_CO":"개업_점포_수"},
                inplace=True)
df_coffee.head()

/Users/mullung/miniforge3/envs/ds2/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

                 프랜차이즈_점포_수  폐업_점포_수  개업_점포_수
y_q_TRDAR_CD_NM
2014_1_계동길                8        4        2
2014_1_난계로27길            10        0        3
2014_1_돈화문로11가길          12        6        3
2014_1_명륜길                2        0        2
2014_1_백석동길               0        0        1

In [29]:
df3 = df3.merge(df_coffee, how='inner', left_index=True, right_index=True)
df3

,한식음식점_개수,중식음식점_개수,일식음식점_개수,양식음식점_개수,패스트푸드점_개수,치킨전문점_개수,프랜차이즈_점포_수,폐업_점포_수,개업_점포_수
y_q_TRDAR_CD_NM,,,,,,,,,
2014_1_계동길,122,6,7.0,34.0,8.0,7,8,4,2
2014_1_난계로27길,223,12,12.0,5.0,7.0,10,10,0,3
2014_1_돈화문로11가길,537,18,19.0,36.0,14.0,10,12,6,3
2014_1_명륜길,42,2,1.0,6.0,5.0,8,2,0,2
2014_1_백석동길,16,0,2.0,6.0,2.0,1,0,0,1
...,...,...,...,...,...,...,...,...,...
2021_2_천호대로197길,57,5,5.0,3.0,5.0,9,4,0,4
2021_2_천호대로219길,85,9,7.0,6.0,5.0,13,4,1,2
2021_2_천호옛14길,189,21,23.0,25.0,19.0,21,22,1,3
2021_2_천호옛길,184,16,23.0,13.0,15.0,23,10,4,2
2021_2_풍성로37가길,134,13,20.0,8.0,12.0,25,3,1,1

# 서울시 상권-추정매출 정보 
- https://data.seoul.go.kr/dataList/OA-15572/S/1/datasetView.do
- THSMON_SELNG_AMT	분기당_매출_금액
- THSMON_SELNG_CO	분기당_매출_건수
- 주중, 주말, 요일별, 시간대별 매출액도 있음

In [30]:
# 2013년부터 있음 but 개수가 적은듯
url = "http://openapi.seoul.go.kr:8088/"+my_key+"/xml/VwsmTrdarSelngQq/1/5/2017/A"
request = urllib.request.Request(url)
response = urllib.request.urlopen(request)
cc = xmltodict.parse(response.read().decode('utf-8')) # return collections.OrderedDict
dd = json.loads(json.dumps(cc)) # return dict
dd

{'VwsmTrdarSelngQq': {'list_total_count': '148852',
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'STDR_YY_CD': '2017',
    'STDR_QU_CD': '3',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1000606',
    'TRDAR_CD_NM': '화곡로44나길',
    'SVC_INDUTY_CD': 'CS200005',
    'SVC_INDUTY_CD_NM': '스포츠 강습',
    'THSMON_SELNG_AMT': '8120355',
    'THSMON_SELNG_CO': '57',
    'MDWK_SELNG_RATE': '100',
    'WKEND_SELNG_RATE': '0',
    'MON_SELNG_RATE': '18',
    'TUES_SELNG_RATE': '0',
    'WED_SELNG_RATE': '15',
    'THUR_SELNG_RATE': '31',
    'FRI_SELNG_RATE': '36',
    'SAT_SELNG_RATE': '0',
    'SUN_SELNG_RATE': '0',
    'TMZON_00_06_SELNG_RATE': '0',
    'TMZON_06_11_SELNG_RATE': '0',
    'TMZON_11_14_SELNG_RATE': '0',
    'TMZON_14_17_SELNG_RATE': '0',
    'TMZON_17_21_SELNG_RATE': '85',
    'TMZON_21_24_SELNG_RATE': '15',
    'ML_SELNG_RATE': '37',
    'FML_SELNG_RATE': '63',
    'AGRDE_10_SELNG_RATE': '0',
    'AGRDE_20_SELNG_RATE': '0',
    'AGRDE_30_SELNG_RATE': '13',
    'AGRDE_40_SELNG_RATE': '84',
    'AGRDE_50_SELNG_RATE': '3',
    'AGRDE_60_ABOVE_SELNG_RATE': '0',
    'MDWK_SELNG_AMT': '8120355',
    'WKEND_SELNG_AMT': '0',
    'MON_SELNG_AMT': '1840590',
    'TUES_SELNG_AMT': '0',
    'WED_SELNG_AMT': '1143324',
    'THUR_SELNG_AMT': '1629611',
    'FRI_SELNG_AMT': '3506830',
    'SAT_SELNG_AMT': '0',
    'SUN_SELNG_AMT': '0',
    'TMZON_00_06_SELNG_AMT': '0',
    'TMZON_06_11_SELNG_AMT': '0',
    'TMZON_11_14_SELNG_AMT': '0',
    'TMZON_14_17_SELNG_AMT': '0',
    'TMZON_17_21_SELNG_AMT': '7164864',
    'TMZON_21_24_SELNG_AMT': '955491',
    'ML_SELNG_AMT': '3224258',
    'FML_SELNG_AMT': '4896097',
    'AGRDE_10_SELNG_AMT': '0',
    'AGRDE_20_SELNG_AMT': '0',
    'AGRDE_30_SELNG_AMT': '1058388',
    'AGRDE_40_SELNG_AMT': '6951347',
    'AGRDE_50_SELNG_AMT': '110620',
    'AGRDE_60_ABOVE_SELNG_AMT': '0',
    'MDWK_SELNG_CO': '57',
    'WKEND_SELNG_CO': '0',
    'MON_SELNG_CO': '11',
    'TUES_SELNG_CO': '0',
    'WED_SELNG_CO': '8',
    'THUR_SELNG_CO': '16',
    'FRI_SELNG_CO': '22',
    'SAT_SELNG_CO': '0',
    'SUN_SELNG_CO': '0',
    'TMZON_00_06_SELNG_CO': '0',
    'TMZON_06_11_SELNG_CO': '0',
    'TMZON_11_14_SELNG_CO': '0',
    'TMZON_14_17_SELNG_CO': '0',
    'TMZON_17_21_SELNG_CO': '49',
    'TMZON_21_24_SELNG_CO': '8',
    'ML_SELNG_CO': '23',
    'FML_SELNG_CO': '34',
    'AGRDE_10_SELNG_CO': '0',
    'AGRDE_20_SELNG_CO': '0',
    'AGRDE_30_SELNG_CO': '8',
    'AGRDE_40_SELNG_CO': '47',
    'AGRDE_50_SELNG_CO': '2',
    'AGRDE_60_ABOVE_SELNG_CO': '0',
    'STOR_CO': '2'},
   {'STDR_YY_CD': '2017',
    'STDR_QU_CD': '4',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1000904',
    'TRDAR_CD_NM': '도곡로37길',
    'SVC_INDUTY_CD': 'CS300031',
    'SVC_INDUTY_CD_NM': '가구',
    'THSMON_SELNG_AMT': '18706204',
    'THSMON_SELNG_CO': '68',
    'MDWK_SELNG_RATE': '49',
    'WKEND_SELNG_RATE': '51',
    'MON_SELNG_RATE': '9',
    'TUES_SELNG_RATE': '0',
    'WED_SELNG_RATE': '24',
    'THUR_SELNG_RATE': '0',
    'FRI_SELNG_RATE': '16',
    'SAT_SELNG_RATE': '42',
    'SUN_SELNG_RATE': '9',
    'TMZON_00_06_SELNG_RATE': '0',
    'TMZON_06_11_SELNG_RATE': '0',
    'TMZON_11_14_SELNG_RATE': '9',
    'TMZON_14_17_SELNG_RATE': '91',
    'TMZON_17_21_SELNG_RATE': '0',
    'TMZON_21_24_SELNG_RATE': '0',
    'ML_SELNG_RATE': '58',
    'FML_SELNG_RATE': '42',
    'AGRDE_10_SELNG_RATE': '0',
    'AGRDE_20_SELNG_RATE': '22',
    'AGRDE_30_SELNG_RATE': '9',
    'AGRDE_40_SELNG_RATE': '12',
    'AGRDE_50_SELNG_RATE': '9',
    'AGRDE_60_ABOVE_SELNG_RATE': '49',
    'MDWK_SELNG_AMT': '13155176',
    'WKEND_SELNG_AMT': '5551028',
    'MON_SELNG_AMT': '2281245',
    'TUES_SELNG_AMT': '0',
    'WED_SELNG_AMT': '10873931',
    'THUR_SELNG_AMT': '0',
    'FRI_SELNG_AMT': '0',
    'SAT_SELNG_AMT': '5018738',
    'SUN_SELNG_AMT': '532290',
    'TMZON_00_06_SELNG_AMT': '0',
    'TMZON_06_11_SELNG_AMT': '0',
    'TMZON_11_14_SELNG_AMT': '1064581',
    'TMZON_14_17_SELNG_AMT': '17641623',
    'TMZON_17_21_SELNG_AMT': '0',
    'TMZON_21_24_SELNG_AMT': '0',
    'ML_SELNG_AMT': '1596871',
    'FML_SELNG_AMT': '14828088',
    'AGRDE_10_SELNG_AMT': '0',
    'AGRDE_20_SELNG_AMT': '0',
    'AGRDE_30_SELNG_AMT': '1064581',
    'AGRDE_40_SELNG_AMT': '532290',
    'AGRDE_50_SELNG_AMT': '10873931',
    'AGRDE_60_ABOVE_SELNG_AMT': '3954157',
    'MDWK_SELNG_CO': '44',
    'WKEND_SELNG_CO': '24',
    'MON_SELNG_CO': '8',
    'TUES_SELNG_CO': '0',
    'WED_SELNG_CO': '22',
    'THUR_SELNG_CO': '0',
    'FRI_SELNG_CO': '14',
    'SAT_SELNG_CO': '16',
    'SUN_SELNG_CO': '8',
    'TMZON_00_06_SELNG_CO': '0',
    'TMZON_06_11_SELNG_CO': '0',
    'TMZON_11_14_SELNG_CO': '8',
    'TMZON_14_17_SELNG_CO': '60',
    'TMZON_17_21_SELNG_CO': '0',
    'TMZON_21_24_SELNG_CO': '0',
    'ML_SELNG_CO': '45',
    'FML_SELNG_CO': '16',
    'AGRDE_10_SELNG_CO': '0',
    'AGRDE_20_SELNG_CO': '15',
    'AGRDE_30_SELNG_CO': '8',
    'AGRDE_40_SELNG_CO': '8',
    'AGRDE_50_SELNG_CO': '8',
    'AGRDE_60_ABOVE_SELNG_CO': '22',
    'STOR_CO': '2'},
   {'STDR_YY_CD': '2017',
    'STDR_QU_CD': '3',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1000205',
    'TRDAR_CD_NM': '전농로4길',
    'SVC_INDUTY_CD': 'CS100008',
    'SVC_INDUTY_CD_NM': '분식전문점',
    'THSMON_SELNG_AMT': '3361476',
    'THSMON_SELNG_CO': '306',
    'MDWK_SELNG_RATE': '95',
    'WKEND_SELNG_RATE': '5',
    'MON_SELNG_RATE': '30',
    'TUES_SELNG_RATE': '14',
    'WED_SELNG_RATE': '16',
    'THUR_SELNG_RATE': '15',
    'FRI_SELNG_RATE': '20',
    'SAT_SELNG_RATE': '5',
    'SUN_SELNG_RATE': '0',
    'TMZON_00_06_SELNG_RATE': '0',
    'TMZON_06_11_SELNG_RATE': '0',
    'TMZON_11_14_SELNG_RATE': '10',
    'TMZON_14_17_SELNG_RATE': '13',
    'TMZON_17_21_SELNG_RATE': '61',
    'TMZON_21_24_SELNG_RATE': '16',
    'ML_SELNG_RATE': '67',
    'FML_SELNG_RATE': '33',
    'AGRDE_10_SELNG_RATE': '4',
    'AGRDE_20_SELNG_RATE': '34',
    'AGRDE_30_SELNG_RATE': '13',
    'AGRDE_40_SELNG_RATE': '23',
    'AGRDE_50_SELNG_RATE': '20',
    'AGRDE_60_ABOVE_SELNG_RATE': '7',
    'MDWK_SELNG_AMT': '3175413',
    'WKEND_SELNG_AMT': '186063',
    'MON_SELNG_AMT': '661577',
    'TUES_SELNG_AMT': '849802',
    'WED_SELNG_AMT': '345252',
    'THUR_SELNG_AMT': '545191',
    'FRI_SELNG_AMT': '773591',
    'SAT_SELNG_AMT': '186063',
    'SUN_SELNG_AMT': '0',
    'TMZON_00_06_SELNG_AMT': '0',
    'TMZON_06_11_SELNG_AMT': '0',
    'TMZON_11_14_SELNG_AMT': '246538',
    'TMZON_14_17_SELNG_AMT': '378853',
    'TMZON_17_21_SELNG_AMT': '1478604',
    'TMZON_21_24_SELNG_AMT': '1257481',
    'ML_SELNG_AMT': '1467355',
    'FML_SELNG_AMT': '1296292',
    'AGRDE_10_SELNG_AMT': '87614',
    'AGRDE_20_SELNG_AMT': '626077',
    'AGRDE_30_SELNG_AMT': '309227',
    'AGRDE_40_SELNG_AMT': '588798',
    'AGRDE_50_SELNG_AMT': '1054538',
    'AGRDE_60_ABOVE_SELNG_AMT': '97395',
    'MDWK_SELNG_CO': '289',
    'WKEND_SELNG_CO': '17',
    'MON_SELNG_CO': '87',
    'TUES_SELNG_CO': '43',
    'WED_SELNG_CO': '52',
    'THUR_SELNG_CO': '47',
    'FRI_SELNG_CO': '60',
    'SAT_SELNG_CO': '17',
    'SUN_SELNG_CO': '0',
    'TMZON_00_06_SELNG_CO': '0',
    'TMZON_06_11_SELNG_CO': '0',
    'TMZON_11_14_SELNG_CO': '32',
    'TMZON_14_17_SELNG_CO': '38',
    'TMZON_17_21_SELNG_CO': '188',
    'TMZON_21_24_SELNG_CO': '48',
    'ML_SELNG_CO': '165',
    'FML_SELNG_CO': '91',
    'AGRDE_10_SELNG_CO': '10',
    'AGRDE_20_SELNG_CO': '74',
    'AGRDE_30_SELNG_CO': '37',
    'AGRDE_40_SELNG_CO': '70',
    'AGRDE_50_SELNG_CO': '48',
    'AGRDE_60_ABOVE_SELNG_CO': '16',
    'STOR_CO': '3'},
   {'STDR_YY_CD': '2017',
    'STDR_QU_CD': '1',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1000125',
    'TRDAR_CD_NM': '한림말3길',
    'SVC_INDUTY_CD': 'CS300013',
    'SVC_INDUTY_CD_NM': '섬유제품',
    'THSMON_SELNG_AMT': '53011206',
    'THSMON_SELNG_CO': '179',
    'MDWK_SELNG_RATE': '94',
    'WKEND_SELNG_RATE': '6',
    'MON_SELNG_RATE': '19',
    'TUES_SELNG_RATE': '8',
    'WED_SELNG_RATE': '24',
    'THUR_SELNG_RATE': '19',
    'FRI_SELNG_RATE': '25',
    'SAT_SELNG_RATE': '6',
    'SUN_SELNG_RATE': '0',
    'TMZON_00_06_SELNG_RATE': '0',
    'TMZON_06_11_SELNG_RATE': '0',
    'TMZON_11_14_SELNG_RATE': '15',
    'TMZON_14_17_SELNG_RATE': '55',
    'TMZON_17_21_SELNG_RATE': '29',
    'TMZON_21_24_SELNG_RATE': '2',
    'ML_SELNG_RATE': '34',
    'FML_SELNG_RATE': '66',
    'AGRDE_10_SELNG_RATE': '0',
    'AGRDE_20_SELNG_RATE': '0',
    'AGRDE_30_SELNG_RATE': '46',
    'AGRDE_40_SELNG_RATE': '33',
    'AGRDE_50_SELNG_RATE': '18',
    'AGRDE_60_ABOVE_SELNG_RATE': '3',
    'MDWK_SELNG_AMT': '44651412',
    'WKEND_SELNG_AMT': '8359794',
    'MON_SELNG_AMT': '3979925',
    'TUES_SELNG_AMT': '4075652',
    'WED_SELNG_AMT': '4053502',
    'THUR_SELNG_AMT': '18343494',
    'FRI_SELNG_AMT': '14198839',
    'SAT_SELNG_AMT': '8359794',
    'SUN_SELNG_AMT': '0',
    'TMZON_00_06_SELNG_AMT': '0',
    'TMZON_06_11_SELNG_AMT': '0',
    'TMZON_11_14_SELNG_AMT': '6059004',
    'TMZON_14_17_SELNG_AMT': '26738733',
    'TMZON_17_21_SELNG_AMT': '19701929',
    'TMZON_21_24_SELNG_AMT': '511540',
    'ML_SELNG_AMT': '18350690',
    'FML_SELNG_AMT': '11097292',
    'AGRDE_10_SELNG_AMT': '0',
    'AGRDE_20_SELNG_AMT': '0',
    'AGRDE_30_SELNG_AMT': '10072654',
    'AGRDE_40_SELNG_AMT': '12790615',
    'AGRDE_50_SELNG_AMT': '6008806',
    'AGRDE_60_ABOVE_SELNG_AMT': '575908',
    'MDWK_SELNG_CO': '168',
    'WKEND_SELNG_CO': '11',
    'MON_SELNG_CO': '34',
    'TUES_SELNG_CO': '18',
    'WED_SELNG_CO': '36',
    'THUR_SELNG_CO': '32',
    'FRI_SELNG_CO': '48',
    'SAT_SELNG_CO': '11',
    'SUN_SELNG_CO': '0',
    'TMZON_00_06_SELNG_CO': '0',
    'TMZON_06_11_SELNG_CO': '0',
    'TMZON_11_14_SELNG_CO': '26',
    'TMZON_14_17_SELNG_CO': '100',
    'TMZON_17_21_SELNG_CO': '50',
    'TMZON_21_24_SELNG_CO': '3',
    'ML_SELNG_CO': '57',
    'FML_SELNG_CO': '107',
    'AGRDE_10_SELNG_CO': '0',
    'AGRDE_20_SELNG_CO': '0',
    'AGRDE_30_SELNG_CO': '64',
    'AGRDE_40_SELNG_CO': '60',
    'AGRDE_50_SELNG_CO': '34',
    'AGRDE_60_ABOVE_SELNG_CO': '5',
    'STOR_CO': '3'},
   {'STDR_YY_CD': '2017',
    'STDR_QU_CD': '1',
    'TRDAR_SE_CD': 'A',
    'TRDAR_SE_CD_NM': '골목상권',
    'TRDAR_CD': '1000624',
    'TRDAR_CD_NM': '고척로52길',
    'SVC_INDUTY_CD': 'CS300013',
    'SVC_INDUTY_CD_NM': '섬유제품',
    'THSMON_SELNG_AMT': '23378194',
    'THSMON_SELNG_CO': '1463',
    'MDWK_SELNG_RATE': '81',
    'WKEND_SELNG_RATE': '19',
    'MON_SELNG_RATE': '17',
    'TUES_SELNG_RATE': '24',
    'WED_SELNG_RATE': '15',
    'THUR_SELNG_RATE': '17',
    'FRI_SELNG_RATE': '10',
    'SAT_SELNG_RATE': '19',
    'SUN_SELNG_RATE': '0',
    'TMZON_00_06_SELNG_RATE': '0',
    'TMZON_06_11_SELNG_RATE': '0',
    'TMZON_11_14_SELNG_RATE': '29',
    'TMZON_14_17_SELNG_RATE': '32',
    'TMZON_17_21_SELNG_RATE': '40',
    'TMZON_21_24_SELNG_RATE': '0',
    'ML_SELNG_RATE': '29',
    'FML_SELNG_RATE': '71',
    'AGRDE_10_SELNG_RATE': '0',
    'AGRDE_20_SELNG_RATE': '6',
    'AGRDE_30_SELNG_RATE': '18',
    'AGRDE_40_SELNG_RATE': '24',
    'AGRDE_50_SELNG_RATE': '40',
    'AGRDE_60_ABOVE_SELNG_RATE': '13',
    'MDWK_SELNG_AMT': '16328912',
    'WKEND_SELNG_AMT': '7049282',
    'MON_SELNG_AMT': '4918794',
    'TUES_SELNG_AMT': '4914526',
    'WED_SELNG_AMT': '2110441',
    'THUR_SELNG_AMT': '3110441',
    'FRI_SELNG_AMT': '1274710',
    'SAT_SELNG_AMT': '7049282',
    'SUN_SELNG_AMT': '0',
    'TMZON_00_06_SELNG_AMT': '0',
    'TMZON_06_11_SELNG_AMT': '0',
    'TMZON_11_14_SELNG_AMT': '7645013',
    'TMZON_14_17_SELNG_AMT': '5560836',
    'TMZON_17_21_SELNG_AMT': '10172345',
    'TMZON_21_24_SELNG_AMT': '0',
    'ML_SELNG_AMT': '9882258',
    'FML_SELNG_AMT': '13237002',
    'AGRDE_10_SELNG_AMT': '0',
    'AGRDE_20_SELNG_AMT': '2049885',
    'AGRDE_30_SELNG_AMT': '2753093',
    'AGRDE_40_SELNG_AMT': '8071092',
    'AGRDE_50_SELNG_AMT': '8208541',
    'AGRDE_60_ABOVE_SELNG_AMT': '2036649',
    'MDWK_SELNG_CO': '1134',
    'WKEND_SELNG_CO': '329',
    'MON_SELNG_CO': '250',
    'TUES_SELNG_CO': '296',
    'WED_SELNG_CO': '213',
    'THUR_SELNG_CO': '209',
    'FRI_SELNG_CO': '166',
    'SAT_SELNG_CO': '329',
    'SUN_SELNG_CO': '0',
    'TMZON_00_06_SELNG_CO': '0',
    'TMZON_06_11_SELNG_CO': '0',
    'TMZON_11_14_SELNG_CO': '419',
    'TMZON_14_17_SELNG_CO': '505',
    'TMZON_17_21_SELNG_CO': '539',
    'TMZON_21_24_SELNG_CO': '0',
    'ML_SELNG_CO': '463',
    'FML_SELNG_CO': '957',
    'AGRDE_10_SELNG_CO': '0',
    'AGRDE_20_SELNG_CO': '93',
    'AGRDE_30_SELNG_CO': '256',
    'AGRDE_40_SELNG_CO': '420',
    'AGRDE_50_SELNG_CO': '481',
    'AGRDE_60_ABOVE_SELNG_CO': '170',
    'STOR_CO': '1'}]}}

In [31]:
def get_Sales(api_key, start, end, year):
    url = f"http://openapi.seoul.go.kr:8088/{api_key}/xml/VwsmTrdarSelngQq/{start}/{end}/{year}"
    request = urllib.request.Request(url)
    response = urllib.request.urlopen(request)
    cc = xmltodict.parse(response.read().decode('utf-8')) # return collections.OrderedDict
    dd = json.loads(json.dumps(cc)) # return dict
    return dd['VwsmTrdarSelngQq']

def get_all_Sales(api_key, year, max_cnt=None):
    if max_cnt == None:
        total_cnt = int(get_Sales(api_key, 1, 1, year).get('list_total_count'))
        print(f'총 {total_cnt} 존재')
    else:
        total_cnt = max_cnt
        print(f'총 {total_cnt}건에 대해 api 호출')
    ls = []
    for start in range(1, total_cnt, 1000):
        get_item = get_Sales(api_key, start, start+999, year)
        ls.extend(get_item['row'])
        print(f'{start} ~ {start+999} 추출 완료')
    return pd.DataFrame(ls)

In [34]:
df_sales_ls = []
for year in range(2014, 2022):
    df_sales = get_all_Sales(my_key, year)
    df_sales_ls.append(df_sales)

총 177230 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
133001 ~ 134000 추출 완료
134001 ~ 135000 추출 완료
135001 ~ 136000 추출 완료
136001 ~ 137000 추출 완료
137001 ~ 138000 추출 완료
138001 ~ 139000 추출 완료
139001 ~ 140000 추출 완료
140001 ~ 141000 추출 완료
141001 ~ 142000 추출 완료
142001 ~ 143000 추출 완료
143001 ~ 144000 추출 완료
144001 ~ 145000 추출 완료
145001 ~ 146000 추출 완료
146001 ~ 147000 추출 완료
147001 ~ 148000 추출 완료
148001 ~ 149000 추출 완료
149001 ~ 150000 추출 완료
150001 ~ 151000 추출 완료
151001 ~ 152000 추출 완료
152001 ~ 153000 추출 완료
153001 ~ 154000 추출 완료
154001 ~ 155000 추출 완료
155001 ~ 156000 추출 완료
156001 ~ 157000 추출 완료
157001 ~ 158000 추출 완료
158001 ~ 159000 추출 완료
159001 ~ 160000 추출 완료
160001 ~ 161000 추출 완료
161001 ~ 162000 추출 완료
162001 ~ 163000 추출 완료
163001 ~ 164000 추출 완료
164001 ~ 165000 추출 완료
165001 ~ 166000 추출 완료
166001 ~ 167000 추출 완료
167001 ~ 168000 추출 완료
168001 ~ 169000 추출 완료
169001 ~ 170000 추출 완료
170001 ~ 171000 추출 완료
171001 ~ 172000 추출 완료
172001 ~ 173000 추출 완료
173001 ~ 174000 추출 완료
174001 ~ 175000 추출 완료
175001 ~ 176000 추출 완료
176001 ~ 177000 추출 완료
177001 ~ 178000 추출 완료
총 132321 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료
65001 ~ 66000 추출 완료
66001 ~ 67000 추출 완료
67001 ~ 68000 추출 완료
68001 ~ 69000 추출 완료
69001 ~ 70000 추출 완료
70001 ~ 71000 추출 완료
71001 ~ 72000 추출 완료
72001 ~ 73000 추출 완료
73001 ~ 74000 추출 완료
74001 ~ 75000 추출 완료
75001 ~ 76000 추출 완료
76001 ~ 77000 추출 완료
77001 ~ 78000 추출 완료
78001 ~ 79000 추출 완료
79001 ~ 80000 추출 완료
80001 ~ 81000 추출 완료
81001 ~ 82000 추출 완료
82001 ~ 83000 추출 완료
83001 ~ 84000 추출 완료
84001 ~ 85000 추출 완료
85001 ~ 86000 추출 완료
86001 ~ 87000 추출 완료
87001 ~ 88000 추출 완료
88001 ~ 89000 추출 완료
89001 ~ 90000 추출 완료
90001 ~ 91000 추출 완료
91001 ~ 92000 추출 완료
92001 ~ 93000 추출 완료
93001 ~ 94000 추출 완료
94001 ~ 95000 추출 완료
95001 ~ 96000 추출 완료
96001 ~ 97000 추출 완료
97001 ~ 98000 추출 완료
98001 ~ 99000 추출 완료
99001 ~ 100000 추출 완료
100001 ~ 101000 추출 완료
101001 ~ 102000 추출 완료
102001 ~ 103000 추출 완료
103001 ~ 104000 추출 완료
104001 ~ 105000 추출 완료
105001 ~ 106000 추출 완료
106001 ~ 107000 추출 완료
107001 ~ 108000 추출 완료
108001 ~ 109000 추출 완료
109001 ~ 110000 추출 완료
110001 ~ 111000 추출 완료
111001 ~ 112000 추출 완료
112001 ~ 113000 추출 완료
113001 ~ 114000 추출 완료
114001 ~ 115000 추출 완료
115001 ~ 116000 추출 완료
116001 ~ 117000 추출 완료
117001 ~ 118000 추출 완료
118001 ~ 119000 추출 완료
119001 ~ 120000 추출 완료
120001 ~ 121000 추출 완료
121001 ~ 122000 추출 완료
122001 ~ 123000 추출 완료
123001 ~ 124000 추출 완료
124001 ~ 125000 추출 완료
125001 ~ 126000 추출 완료
126001 ~ 127000 추출 완료
127001 ~ 128000 추출 완료
128001 ~ 129000 추출 완료
129001 ~ 130000 추출 완료
130001 ~ 131000 추출 완료
131001 ~ 132000 추출 완료
132001 ~ 133000 추출 완료
총 64738 존재
1 ~ 1000 추출 완료
1001 ~ 2000 추출 완료
2001 ~ 3000 추출 완료
3001 ~ 4000 추출 완료
4001 ~ 5000 추출 완료
5001 ~ 6000 추출 완료
6001 ~ 7000 추출 완료
7001 ~ 8000 추출 완료
8001 ~ 9000 추출 완료
9001 ~ 10000 추출 완료
10001 ~ 11000 추출 완료
11001 ~ 12000 추출 완료
12001 ~ 13000 추출 완료
13001 ~ 14000 추출 완료
14001 ~ 15000 추출 완료
15001 ~ 16000 추출 완료
16001 ~ 17000 추출 완료
17001 ~ 18000 추출 완료
18001 ~ 19000 추출 완료
19001 ~ 20000 추출 완료
20001 ~ 21000 추출 완료
21001 ~ 22000 추출 완료
22001 ~ 23000 추출 완료
23001 ~ 24000 추출 완료
24001 ~ 25000 추출 완료
25001 ~ 26000 추출 완료
26001 ~ 27000 추출 완료
27001 ~ 28000 추출 완료
28001 ~ 29000 추출 완료
29001 ~ 30000 추출 완료
30001 ~ 31000 추출 완료
31001 ~ 32000 추출 완료
32001 ~ 33000 추출 완료
33001 ~ 34000 추출 완료
34001 ~ 35000 추출 완료
35001 ~ 36000 추출 완료
36001 ~ 37000 추출 완료
37001 ~ 38000 추출 완료
38001 ~ 39000 추출 완료
39001 ~ 40000 추출 완료
40001 ~ 41000 추출 완료
41001 ~ 42000 추출 완료
42001 ~ 43000 추출 완료
43001 ~ 44000 추출 완료
44001 ~ 45000 추출 완료
45001 ~ 46000 추출 완료
46001 ~ 47000 추출 완료
47001 ~ 48000 추출 완료
48001 ~ 49000 추출 완료
49001 ~ 50000 추출 완료
50001 ~ 51000 추출 완료
51001 ~ 52000 추출 완료
52001 ~ 53000 추출 완료
53001 ~ 54000 추출 완료
54001 ~ 55000 추출 완료
55001 ~ 56000 추출 완료
56001 ~ 57000 추출 완료
57001 ~ 58000 추출 완료
58001 ~ 59000 추출 완료
59001 ~ 60000 추출 완료
60001 ~ 61000 추출 완료
61001 ~ 62000 추출 완료
62001 ~ 63000 추출 완료
63001 ~ 64000 추출 완료
64001 ~ 65000 추출 완료

In [35]:
df_sales_all = pd.concat( df_sales_ls)
df_sales_all

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,THSMON_SELNG_AMT,THSMON_SELNG_CO,...,TMZON_21_24_SELNG_CO,ML_SELNG_CO,FML_SELNG_CO,AGRDE_10_SELNG_CO,AGRDE_20_SELNG_CO,AGRDE_30_SELNG_CO,AGRDE_40_SELNG_CO,AGRDE_50_SELNG_CO,AGRDE_60_ABOVE_SELNG_CO,STOR_CO
0,2019,4,A,골목상권,1000653,중앙로1길,CS300020,서적,8897598,275,...,12,131,144,0,0,24,251,0,0,1
1,2019,3,A,골목상권,1000523,목동중앙남로3가길,CS300022,화장품,261449372,616,...,0,65,551,0,140,167,104,168,37,9
2,2019,1,R,전통시장,1001347,석관황금시장,CS300011,일반의류,4584906,102,...,0,0,102,0,0,0,0,0,102,6
3,2019,1,A,골목상권,1000348,한천로130길,CS300021,문구,2217625,201,...,0,67,101,0,34,0,134,0,0,3
4,2019,1,A,골목상권,1000345,인수봉로79길,CS200003,예술학원,1974684,16,...,0,0,16,0,0,16,0,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64733,2021,2,U,관광특구,1001496,강남 마이스 관광특구,CS300028,화초,1026839343,22212,...,585,8998,12018,36,6420,7344,3521,2384,1311,6
64734,2021,2,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,11019599281,5852,...,0,2419,3433,0,97,544,1274,1655,2282,6
64735,2021,2,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,1829845301,8110,...,90,4012,3729,84,1750,2096,1986,882,943,8
64736,2021,2,U,관광특구,1001496,강남 마이스 관광특구,CS300035,인테리어,86120359,739,...,0,370,0,0,0,0,370,0,0,4
64737,2021,2,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,5836078,92,...,0,14,74,0,27,42,5,5,9,8

In [59]:
df_sales_all.to_csv("sales_raw.csv")

In [49]:
df_sales_all = pd.read_csv('sales_raw.csv', index_col=0)
df_sales_all.head(3)

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,THSMON_SELNG_AMT,THSMON_SELNG_CO,...,TMZON_21_24_SELNG_CO,ML_SELNG_CO,FML_SELNG_CO,AGRDE_10_SELNG_CO,AGRDE_20_SELNG_CO,AGRDE_30_SELNG_CO,AGRDE_40_SELNG_CO,AGRDE_50_SELNG_CO,AGRDE_60_ABOVE_SELNG_CO,STOR_CO
0,2019,4,A,골목상권,1000653,중앙로1길,CS300020,서적,8897598,275,...,12,131,144,0,0,24,251,0,0,1
1,2019,3,A,골목상권,1000523,목동중앙남로3가길,CS300022,화장품,261449372,616,...,0,65,551,0,140,167,104,168,37,9
2,2019,1,R,전통시장,1001347,석관황금시장,CS300011,일반의류,4584906,102,...,0,0,102,0,0,0,0,0,102,6

In [50]:
df_sales_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1495094 entries, 0 to 222261
Data columns (total 80 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   STDR_YY_CD                 1495094 non-null  int64
 1   STDR_QU_CD                 1495094 non-null  int64
 2   TRDAR_SE_CD                1495094 non-null  object
 3   TRDAR_SE_CD_NM             1495094 non-null  object
 4   TRDAR_CD                   1495094 non-null  int64
 5   TRDAR_CD_NM                1495094 non-null  object
 6   SVC_INDUTY_CD              1495094 non-null  object
 7   SVC_INDUTY_CD_NM           1495094 non-null  object
 8   THSMON_SELNG_AMT           1495094 non-null  int64
 9   THSMON_SELNG_CO            1495094 non-null  int64
 10  MDWK_SELNG_RATE            1495094 non-null  int64
 11  WKEND_SELNG_RATE           1495094 non-null  int64
 12  MON_SELNG_RATE             1495094 non-null  int64
 13  TUES_SELNG_RATE            1495094 non-null  int64
 14  WED_SELNG_RATE             1495094 non-null  int64
 15  THUR_SELNG_RATE            1495094 non-null  int64
 16  FRI_SELNG_RATE             1495094 non-null  int64
 17  SAT_SELNG_RATE             1495094 non-null  int64
 18  SUN_SELNG_RATE             1495094 non-null  int64
 19  TMZON_00_06_SELNG_RATE     1495094 non-null  int64
 20  TMZON_06_11_SELNG_RATE     1495094 non-null  int64
 21  TMZON_11_14_SELNG_RATE     1495094 non-null  int64
 22  TMZON_14_17_SELNG_RATE     1495094 non-null  int64
 23  TMZON_17_21_SELNG_RATE     1495094 non-null  int64
 24  TMZON_21_24_SELNG_RATE     1495094 non-null  int64
 25  ML_SELNG_RATE              1495094 non-null  int64
 26  FML_SELNG_RATE             1495094 non-null  int64
 27  AGRDE_10_SELNG_RATE        1495094 non-null  int64
 28  AGRDE_20_SELNG_RATE        1495094 non-null  int64
 29  AGRDE_30_SELNG_RATE        1495094 non-null  int64
 30  AGRDE_40_SELNG_RATE        1495094 non-null  int64
 31  AGRDE_50_SELNG_RATE        1495094 non-null  int64
 32  AGRDE_60_ABOVE_SELNG_RATE  1495094 non-null  int64
 33  MDWK_SELNG_AMT             1495094 non-null  int64
 34  WKEND_SELNG_AMT            1495094 non-null  int64
 35  MON_SELNG_AMT              1495094 non-null  int64
 36  TUES_SELNG_AMT             1495094 non-null  int64
 37  WED_SELNG_AMT              1495094 non-null  int64
 38  THUR_SELNG_AMT             1495094 non-null  int64
 39  FRI_SELNG_AMT              1495094 non-null  int64
 40  SAT_SELNG_AMT              1495094 non-null  int64
 41  SUN_SELNG_AMT              1495094 non-null  int64
 42  TMZON_00_06_SELNG_AMT      1495094 non-null  int64
 43  TMZON_06_11_SELNG_AMT      1495094 non-null  int64
 44  TMZON_11_14_SELNG_AMT      1495094 non-null  int64
 45  TMZON_14_17_SELNG_AMT      1495094 non-null  int64
 46  TMZON_17_21_SELNG_AMT      1495094 non-null  int64
 47  TMZON_21_24_SELNG_AMT      1495094 non-null  int64
 48  ML_SELNG_AMT               1495094 non-null  int64
 49  FML_SELNG_AMT              1495094 non-null  int64
 50  AGRDE_10_SELNG_AMT         1495094 non-null  int64
 51  AGRDE_20_SELNG_AMT         1495094 non-null  int64
 52  AGRDE_30_SELNG_AMT         1495094 non-null  int64
 53  AGRDE_40_SELNG_AMT         1495094 non-null  int64
 54  AGRDE_50_SELNG_AMT         1495094 non-null  int64
 55  AGRDE_60_ABOVE_SELNG_AMT   1495094 non-null  int64
 56  MDWK_SELNG_CO              1495094 non-null  int64
 57  WKEND_SELNG_CO             1495094 non-null  int64
 58  MON_SELNG_CO               1495094 non-null  int64
 59  TUES_SELNG_CO              1495094 non-null  int64
 60  WED_SELNG_CO               1495094 non-null  int64
 61  THUR_SELNG_CO              1495094 non-null  int64
 62  FRI_SELNG_CO               1495094 non-null  int64
 63  SAT_SELNG_CO               1495094 non-null  int64
 64  SUN_SELNG_CO               1495094 non-null  int64
 65  TMZON_00_06_SELNG_CO       1495094 non-null  int64
 66  TMZON_06_11_SELNG_CO       1495094 non-null  int64
 67  TMZON_11_14_SELNG_CO       1495094 non-null  int64
 68  TMZON_14_17_SELNG_CO       1495094 non-null  int64
 69  TMZON_17_21_SELNG_CO       1495094 non-null  int64
 70  TMZON_21_24_SELNG_CO       1495094 non-null  int64
 71  ML_SELNG_CO                1495094 non-null  int64
 72  FML_SELNG_CO               1495094 non-null  int64
 73  AGRDE_10_SELNG_CO          1495094 non-null  int64
 74  AGRDE_20_SELNG_CO          1495094 non-null  int64
 75  AGRDE_30_SELNG_CO          1495094 non-null  int64
 76  AGRDE_40_SELNG_CO          1495094 non-null  int64
 77  AGRDE_50_SELNG_CO          1495094 non-null  int64
 78  AGRDE_60_ABOVE_SELNG_CO    1495094 non-null  int64
 79  STOR_CO                    1495094 non-null  int64
dtypes: int64(75), object(5)
memory usage: 923.9+ MB

In [51]:
df_sales_all['y_q_TRDAR_CD_NM'] = df_sales_all['STDR_YY_CD'].astype(str) + "_" + df_sales_all['STDR_QU_CD'].astype(str) + "_" +df_sales_all['TRDAR_CD_NM']
df_sales_all.set_index('y_q_TRDAR_CD_NM', inplace=True)
df_sales_all.head()

,STDR_YY_CD,STDR_QU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SVC_INDUTY_CD,SVC_INDUTY_CD_NM,THSMON_SELNG_AMT,THSMON_SELNG_CO,...,TMZON_21_24_SELNG_CO,ML_SELNG_CO,FML_SELNG_CO,AGRDE_10_SELNG_CO,AGRDE_20_SELNG_CO,AGRDE_30_SELNG_CO,AGRDE_40_SELNG_CO,AGRDE_50_SELNG_CO,AGRDE_60_ABOVE_SELNG_CO,STOR_CO
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,,,,,,,
2019_4_중앙로1길,2019,4,A,골목상권,1000653,중앙로1길,CS300020,서적,8897598,275,...,12,131,144,0,0,24,251,0,0,1
2019_3_목동중앙남로3가길,2019,3,A,골목상권,1000523,목동중앙남로3가길,CS300022,화장품,261449372,616,...,0,65,551,0,140,167,104,168,37,9
2019_1_석관황금시장,2019,1,R,전통시장,1001347,석관황금시장,CS300011,일반의류,4584906,102,...,0,0,102,0,0,0,0,0,102,6
2019_1_한천로130길,2019,1,A,골목상권,1000348,한천로130길,CS300021,문구,2217625,201,...,0,67,101,0,34,0,134,0,0,3
2019_1_인수봉로79길,2019,1,A,골목상권,1000345,인수봉로79길,CS200003,예술학원,1974684,16,...,0,0,16,0,0,16,0,0,0,6

In [52]:
df_sales_all.index.unique()

Index(['2019_4_중앙로1길', '2019_3_목동중앙남로3가길', '2019_1_석관황금시장', '2019_1_한천로130길',
       '2019_1_인수봉로79길', '2019_1_대흥로28길', '2019_1_남현3길',
       '2019_1_서울 종로구 종로5가역_3', '2019_1_증가로10길', '2019_2_영등포청과시장',
       ...
       '2018_3_논현종합시장', '2018_3_푸른터시장', '2018_3_유영시장', '2018_3_수유북부시장',
       '2018_3_박미시장', '2018_4_수유북부시장', '2018_4_푸른터시장', '2018_4_박미시장',
       '2018_4_논현종합시장', '2018_4_유영시장'],
      dtype='object', name='y_q_TRDAR_CD_NM', length=44717)

In [53]:
df_sales_all['SVC_INDUTY_CD_NM'].unique()

array(['서적', '화장품', '일반의류', '문구', '예술학원', '세탁소', '시계및귀금속', '스포츠 강습',
       '자전거 및 기타운송장비', '양식음식점', '반찬가게', '호프-간이주점', '일반교습학원', '컴퓨터및주변장치판매',
       '한식음식점', '의료기기', '가전제품', '육류판매', '일식음식점', '커피-음료', '치과의원', '여관',
       '섬유제품', '제과점', '조명용품', '의약품', '화초', '신발', '편의점', '골프연습장', '철물점',
       '한의원', '패스트푸드점', '슈퍼마켓', '일반의원', '미용실', '외국어학원', '노래방', '분식전문점',
       '중식음식점', '자동차수리', '가전제품수리', '당구장', '치킨전문점', '애완동물', '청과상', '자동차미용',
       '네일숍', '가구', 'PC방', '미곡판매', '운동/경기용품', '피부관리실', '안경', '스포츠클럽',
       '수산물판매', '고시원', '인테리어', '가방', '완구', '전자상거래업', '핸드폰', '부동산중개업',
       '기타법무서비스', '유아의류', '동물병원', '회계사사무소', '법무사사무소', '주류도매', '컴퓨터학원',
       '변리사사무소', '볼링장', '변호사사무소', '세무사사무소', '한복점', '자동차부품', '여행사', '사진관',
       '독서실', '예술품', '패션용품', '예체능학원', '가구·가전', '두발미용업', '식료품', '건강보조식품',
       '주방·가정용품', '자동차수리·세차', '오락·운동', '화초·애완', '숙박업', '통신판매업', '호프·간이주점',
       '의약·의료용품', '세탁소(가정)', '의류점', '서적·문구', '커피·음료', '통신기기수리',
       '컴퓨터·주변기기', '악기', '주유소', '중고차판매', '건축물청소', '전자게임장', '비디오/서적임대'],
      dtype=object)

In [54]:
need_industry_ls = ['커피-음료',  # Target(종속변수) 후보
                    '일반교습학원', '스포츠 강습', '예술학원', # 학문/교육업종
                    '피부관리실', '미용실', '네일숍', # 요가/단전/마사지업종??
                    '인테리어',  #인테리어/소품
                    '일식음식점', '양식음식점', '한식음식점', '중식음식점', '분식전문점'] # 식당

In [55]:
# THSMON_SELNG_AMT 분기당_매출_금액
# THSMON_SELNG_CO 분기당_매출_건수
def get_industry_sales(df_sales, industry):
    df_industry = df_sales[df_sales['SVC_INDUTY_CD_NM']==industry][['THSMON_SELNG_AMT','THSMON_SELNG_CO']]
    df_industry.rename(columns={"THSMON_SELNG_AMT": industry + "_분기당_매출_금액", 
                                "THSMON_SELNG_CO": industry + "_분기당_매출_건수"},
                       inplace=True)
    return df_industry

def get_all_industry_sales(df_sales, need_industry_ls):
    df = pd.DataFrame(index=df_sales.index.unique())
    for industry in need_industry_ls:
        df_industry = get_industry_sales(df_sales, industry)
        df = df.merge(df_industry, how='left', left_index=True, right_index=True)
        
    return df

In [57]:
df_sales2 = get_all_industry_sales(df_sales_all, need_industry_ls)
df_sales2

,커피-음료_분기당_매출_금액,커피-음료_분기당_매출_건수,일반교습학원_분기당_매출_금액,일반교습학원_분기당_매출_건수,스포츠 강습_분기당_매출_금액,스포츠 강습_분기당_매출_건수,예술학원_분기당_매출_금액,예술학원_분기당_매출_건수,피부관리실_분기당_매출_금액,피부관리실_분기당_매출_건수,...,일식음식점_분기당_매출_금액,일식음식점_분기당_매출_건수,양식음식점_분기당_매출_금액,양식음식점_분기당_매출_건수,한식음식점_분기당_매출_금액,한식음식점_분기당_매출_건수,중식음식점_분기당_매출_금액,중식음식점_분기당_매출_건수,분식전문점_분기당_매출_금액,분식전문점_분기당_매출_건수
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,,,,,,,
2014_1_가락시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.069821e+09,70121.0,NaN,NaN,47983690.0,2362.0
2014_1_가락시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.069821e+09,70121.0,NaN,NaN,47983690.0,2362.0
2014_1_가로공원로58길,NaN,NaN,6440417.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.114176e+07,618.0,NaN,NaN,NaN,NaN
2014_1_가로공원로76가길,4.369349e+06,754.0,37625519.0,128.0,4293085.0,37.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.290596e+07,2175.0,NaN,NaN,3388177.0,358.0
2014_1_가로공원로80길,NaN,NaN,51925963.0,173.0,3324820.0,27.0,29093140.0,264.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.922635e+08,6549.0,NaN,NaN,6401285.0,697.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021_2_휘경로2길,1.237502e+09,139071.0,171764504.0,453.0,NaN,NaN,NaN,NaN,NaN,NaN,...,94463494.0,5024.0,165172719.0,6501.0,1.373979e+09,83896.0,108084827.0,7610.0,224492711.0,16350.0
2021_2_휘경로3길,8.082230e+07,25812.0,NaN,NaN,NaN,NaN,NaN,NaN,3538057.0,35.0,...,135363203.0,9295.0,9733810.0,235.0,1.865704e+09,80101.0,365395068.0,11670.0,25558015.0,2102.0
2021_2_흑석로13길,NaN,NaN,20489486.0,96.0,NaN,NaN,NaN,NaN,NaN,NaN,...,674053255.0,21678.0,NaN,NaN,3.375852e+08,7140.0,NaN,NaN,29120066.0,3652.0
2021_2_흑석로9길,2.854537e+08,42475.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43934449.0,3922.0,143990813.0,8965.0,8.166552e+08,49124.0,50068070.0,3463.0,563289600.0,46487.0
2021_2_흑석시장,1.063761e+08,11710.0,21000000.0,82.0,226426595.0,3818.0,99721698.0,691.0,244828234.0,840.0,...,39909132.0,683.0,34322457.0,3051.0,2.766305e+09,68861.0,234257249.0,4402.0,78650103.0,9497.0

In [60]:
df_sales_all['TRDAR_SE_CD'].unique()

array(['A', 'R', 'D', 'U'], dtype=object)

In [61]:
df3.head(3)

,한식음식점_개수,중식음식점_개수,일식음식점_개수,양식음식점_개수,패스트푸드점_개수,치킨전문점_개수,프랜차이즈_점포_수,폐업_점포_수,개업_점포_수
y_q_TRDAR_CD_NM,,,,,,,,,
2014_1_계동길,122,6,7.0,34.0,8.0,7,8,4,2
2014_1_난계로27길,223,12,12.0,5.0,7.0,10,10,0,3
2014_1_돈화문로11가길,537,18,19.0,36.0,14.0,10,12,6,3

In [63]:
df_sales2.head(3)

,커피-음료_분기당_매출_금액,커피-음료_분기당_매출_건수,일반교습학원_분기당_매출_금액,일반교습학원_분기당_매출_건수,스포츠 강습_분기당_매출_금액,스포츠 강습_분기당_매출_건수,예술학원_분기당_매출_금액,예술학원_분기당_매출_건수,피부관리실_분기당_매출_금액,피부관리실_분기당_매출_건수,...,일식음식점_분기당_매출_금액,일식음식점_분기당_매출_건수,양식음식점_분기당_매출_금액,양식음식점_분기당_매출_건수,한식음식점_분기당_매출_금액,한식음식점_분기당_매출_건수,중식음식점_분기당_매출_금액,중식음식점_분기당_매출_건수,분식전문점_분기당_매출_금액,분식전문점_분기당_매출_건수
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,,,,,,,
2014_1_가락시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.069821e+09,70121.0,NaN,NaN,47983690.0,2362.0
2014_1_가락시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.069821e+09,70121.0,NaN,NaN,47983690.0,2362.0
2014_1_가로공원로58길,NaN,NaN,6440417.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.114176e+07,618.0,NaN,NaN,NaN,NaN

In [65]:
df_sanggwan = df3.merge(df_sales2, how='inner', left_index=True, right_index=True)

In [80]:
index_split = pd.Series(df_sanggwan.index).apply(lambda x: x.split('_')).values
index_split = pd.DataFrame(list(index_split), columns=['Year', 'Quater', 'Load_NM'], index=df_sanggwan.index)
index_split

                  Year Quater    Load_NM
y_q_TRDAR_CD_NM
2014_1_가로공원로58길   2014      1   가로공원로58길
2014_1_가로공원로76가길  2014      1  가로공원로76가길
2014_1_가로공원로80길   2014      1   가로공원로80길
2014_1_가로공원로80길   2014      1   가로공원로80길
2014_1_가마산로61길    2014      1    가마산로61길
...                ...    ...        ...
2021_2_휘경로23길     2021      2     휘경로23길
2021_2_휘경로2길      2021      2      휘경로2길
2021_2_휘경로3길      2021      2      휘경로3길
2021_2_흑석로13길     2021      2     흑석로13길
2021_2_흑석로9길      2021      2      흑석로9길

[60287 rows x 3 columns]

In [81]:
df_sanggwan['Year'] = index_split['Year']
df_sanggwan['Quater'] = index_split['Quater']
df_sanggwan['Load_NM'] = index_split['Load_NM']
df_sanggwan

,한식음식점_개수,중식음식점_개수,일식음식점_개수,양식음식점_개수,패스트푸드점_개수,치킨전문점_개수,프랜차이즈_점포_수,폐업_점포_수,개업_점포_수,커피-음료_분기당_매출_금액,...,양식음식점_분기당_매출_건수,한식음식점_분기당_매출_금액,한식음식점_분기당_매출_건수,중식음식점_분기당_매출_금액,중식음식점_분기당_매출_건수,분식전문점_분기당_매출_금액,분식전문점_분기당_매출_건수,Year,Quater,Load_NM
y_q_TRDAR_CD_NM,,,,,,,,,,,,,,,,,,,,,
2014_1_가로공원로58길,49,1,2.0,1.0,4.0,10,0,1,0,NaN,...,NaN,2.114176e+07,618.0,NaN,NaN,NaN,NaN,2014,1,가로공원로58길
2014_1_가로공원로76가길,162,9,6.0,3.0,8.0,22,3,1,1,4.369349e+06,...,NaN,8.290596e+07,2175.0,NaN,NaN,3388177.0,358.0,2014,1,가로공원로76가길
2014_1_가로공원로80길,77,8,4.0,1.0,7.0,13,1,1,1,NaN,...,NaN,1.922635e+08,6549.0,NaN,NaN,6401285.0,697.0,2014,1,가로공원로80길
2014_1_가로공원로80길,77,8,4.0,1.0,7.0,13,1,1,1,NaN,...,NaN,1.922635e+08,6549.0,NaN,NaN,6401285.0,697.0,2014,1,가로공원로80길
2014_1_가마산로61길,83,12,1.0,0.0,6.0,12,0,0,0,NaN,...,NaN,2.093439e+08,5905.0,33505801.0,1793.0,876152.0,131.0,2014,1,가마산로61길
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021_2_휘경로23길,43,5,2.0,4.0,5.0,8,3,0,1,NaN,...,NaN,2.100000e+07,1668.0,NaN,NaN,NaN,NaN,2021,2,휘경로23길
2021_2_휘경로2길,110,12,10.0,18.0,18.0,13,13,2,2,1.237502e+09,...,6501.0,1.373979e+09,83896.0,108084827.0,7610.0,224492711.0,16350.0,2021,2,휘경로2길
2021_2_휘경로3길,124,15,10.0,17.0,21.0,20,14,2,2,8.082230e+07,...,235.0,1.865704e+09,80101.0,365395068.0,11670.0,25558015.0,2102.0,2021,2,휘경로3길
2021_2_흑석로13길,118,13,15.0,14.0,16.0,19,18,0,1,NaN,...,NaN,3.375852e+08,7140.0,NaN,NaN,29120066.0,3652.0,2021,2,흑석로13길
2021_2_흑석로9길,102,13,16.0,14.0,16.0,19,17,0,1,2.854537e+08,...,8965.0,8.166552e+08,49124.0,50068070.0,3463.0,563289600.0,46487.0,2021,2,흑석로9길

In [82]:
df_sanggwan.to_csv("df_sanggwan.csv")

In [83]:
df_sanggwan = pd.read_csv("df_sanggwan.csv", index_col=0)
df_sanggwan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60287 entries, 2014_1_가로공원로58길 to 2021_2_흑석로9길
Data columns (total 38 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   한식음식점_개수          60287 non-null  int64
 1   중식음식점_개수          60287 non-null  int64
 2   일식음식점_개수          60205 non-null  float64
 3   양식음식점_개수          60254 non-null  float64
 4   패스트푸드점_개수         60273 non-null  float64
 5   치킨전문점_개수          60287 non-null  int64
 6   프랜차이즈_점포_수        60287 non-null  int64
 7   폐업_점포_수           60287 non-null  int64
 8   개업_점포_수           60287 non-null  int64
 9   커피-음료_분기당_매출_금액   53272 non-null  float64
 10  커피-음료_분기당_매출_건수   53272 non-null  float64
 11  일반교습학원_분기당_매출_금액  38026 non-null  float64
 12  일반교습학원_분기당_매출_건수  38026 non-null  float64
 13  스포츠 강습_분기당_매출_금액  31361 non-null  float64
 14  스포츠 강습_분기당_매출_건수  31361 non-null  float64
 15  예술학원_분기당_매출_금액    35735 non-null  float64
 16  예술학원_분기당_매출_건수    35735 non-null  float64
 17  피부관리실_분기당_매출_금액   34998 non-null  float64
 18  피부관리실_분기당_매출_건수   34998 non-null  float64
 19  미용실_분기당_매출_금액     57774 non-null  float64
 20  미용실_분기당_매출_건수     57774 non-null  float64
 21  네일숍_분기당_매출_금액     26989 non-null  float64
 22  네일숍_분기당_매출_건수     26989 non-null  float64
 23  인테리어_분기당_매출_금액    20425 non-null  float64
 24  인테리어_분기당_매출_건수    20425 non-null  float64
 25  일식음식점_분기당_매출_금액   23939 non-null  float64
 26  일식음식점_분기당_매출_건수   23939 non-null  float64
 27  양식음식점_분기당_매출_금액   21325 non-null  float64
 28  양식음식점_분기당_매출_건수   21325 non-null  float64
 29  한식음식점_분기당_매출_금액   59296 non-null  float64
 30  한식음식점_분기당_매출_건수   59296 non-null  float64
 31  중식음식점_분기당_매출_금액   39627 non-null  float64
 32  중식음식점_분기당_매출_건수   39627 non-null  float64
 33  분식전문점_분기당_매출_금액   52812 non-null  float64
 34  분식전문점_분기당_매출_건수   52812 non-null  float64
 35  Year              60287 non-null  int64
 36  Quater            60287 non-null  int64
 37  Load_NM           60287 non-null  object
dtypes: float64(29), int64(8), object(1)
memory usage: 17.9+ MB

# 스타벅스

In [84]:
df = pd.read_csv("fulldata_07_24_05_P_휴게음식점.csv", sep=',', encoding='cp949', dtype="object")
df.head()

,번호,개방서비스명,개방서비스id,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지,Unnamed: 47
0,1,휴게음식점,07_24_05_P,3910000,3910038-104-2020-00083,20201209,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,72,NaN,NaN,NaN,NaN
1,2,휴게음식점,07_24_05_P,3900000,3900000-104-2020-00112,20201209,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,9.87,NaN,NaN,NaN,NaN
2,3,휴게음식점,07_24_05_P,3700000,3700000-104-2020-00261,20201209,NaN,03,폐업,02,...,0,NaN,0,0,N,17.06,NaN,NaN,NaN,NaN
3,4,휴게음식점,07_24_05_P,3160000,3160000-104-2021-00019,20210202,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,23.56,NaN,NaN,NaN,NaN
4,5,휴게음식점,07_24_05_P,3160000,3160000-104-2018-00175,20181210,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,14.88,NaN,NaN,NaN,NaN

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478663 entries, 0 to 478662
Data columns (total 48 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   번호           478663 non-null  object
 1   개방서비스명       478663 non-null  object
 2   개방서비스id      478663 non-null  object
 3   개방자치단체코드     478663 non-null  object
 4   관리번호         478663 non-null  object
 5   인허가일자        478663 non-null  object
 6   인허가취소일자      0 non-null       object
 7   영업상태구분코드     478663 non-null  object
 8   영업상태명        478663 non-null  object
 9   상세영업상태코드     478663 non-null  object
 10  상세영업상태명      478663 non-null  object
 11  폐업일자         289077 non-null  object
 12  휴업시작일자       0 non-null       object
 13  휴업종료일자       0 non-null       object
 14  재개업일자        0 non-null       object
 15  소재지전화        243247 non-null  object
 16  소재지면적        442984 non-null  object
 17  소재지우편번호      462121 non-null  object
 18  소재지전체주소      476803 non-null  object
 19  도로명전체주소      339351 non-null  object
 20  도로명우편번호      334604 non-null  object
 21  사업장명         478663 non-null  object
 22  최종수정시점       478663 non-null  object
 23  데이터갱신구분      478663 non-null  object
 24  데이터갱신일자      478663 non-null  object
 25  업태구분명        478645 non-null  object
 26  좌표정보(x)      457149 non-null  object
 27  좌표정보(y)      457149 non-null  object
 28  위생업태명        478644 non-null  object
 29  남성종사자수       153086 non-null  object
 30  여성종사자수       158288 non-null  object
 31  영업장주변구분명     138509 non-null  object
 32  등급구분명        68395 non-null   object
 33  급수시설구분명      286572 non-null  object
 34  총종업원수        22755 non-null   object
 35  본사종업원수       27387 non-null   object
 36  공장사무직종업원수    27387 non-null   object
 37  공장판매직종업원수    27387 non-null   object
 38  공장생산직종업원수    27387 non-null   object
 39  건물소유구분명      16 non-null      object
 40  보증액          27381 non-null   object
 41  월세액          27381 non-null   object
 42  다중이용업소여부     478662 non-null  object
 43  시설총규모        478662 non-null  object
 44  전통업소지정번호     725 non-null     object
 45  전통업소주된음식     7 non-null       object
 46  홈페이지         0 non-null       object
 47  Unnamed: 47  0 non-null       object
dtypes: object(48)
memory usage: 175.3+ MB

In [86]:
star_bucks_df = df[df['사업장명'].apply(lambda x: True if x.find("스타벅스") != -1 else False)]
star_bucks_df

,번호,개방서비스명,개방서비스id,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지,Unnamed: 47
3359,3360,휴게음식점,07_24_05_P,3130000,3130000-104-2014-00140,20140624,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,252.76,NaN,NaN,NaN,NaN
9043,9044,휴게음식점,07_24_05_P,3910000,3910000-104-2009-00036,20090422,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,145.43,NaN,NaN,NaN,NaN
10802,10803,휴게음식점,07_24_05_P,3820000,3820000-104-2008-00088,20081127,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,391.92,NaN,NaN,NaN,NaN
11601,11602,휴게음식점,07_24_05_P,5600000,5600000-104-2013-00039,20130703,NaN,03,폐업,02,...,0,NaN,0,0,N,159.67,NaN,NaN,NaN,NaN
19227,19228,휴게음식점,07_24_05_P,3520000,3520000-104-2011-00044,20110525,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,222.52,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478233,478234,휴게음식점,07_24_05_P,3420000,3420000-104-2014-00058,20140527,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,Y,260,NaN,NaN,NaN,NaN
478372,478373,휴게음식점,07_24_05_P,3480000,3480000-104-2015-00059,20151008,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,341.42,NaN,NaN,NaN,NaN
478521,478522,휴게음식점,07_24_05_P,3470000,3470000-104-2012-00118,20120917,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,251.7,NaN,NaN,NaN,NaN
478560,478561,휴게음식점,07_24_05_P,3420000,3420000-104-2013-00002,20130109,NaN,01,영업/정상,01,...,0,NaN,0,0,Y,366.93,NaN,NaN,NaN,NaN
478645,478646,휴게음식점,07_24_05_P,3420000,3420000-104-2011-00093,20110811,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,Y,252,NaN,NaN,NaN,NaN

In [92]:
region_code = pd.read_excel("./localdata_SampleSource/[붙임1] 지방행정인허가데이터개방_자치단체코드목록.xlsx").ffill()
region_code

      번호      시도명  시도(자치단체)코드  시군구명  시군구(자치단체)코드
0      1    서울특별시   6110000.0   종로구    3000000.0
1      2    서울특별시   6110000.0    중구    3010000.0
2      3    서울특별시   6110000.0   용산구    3020000.0
3      4    서울특별시   6110000.0   성동구    3030000.0
4      5    서울특별시   6110000.0   광진구    3040000.0
..   ...      ...         ...   ...          ...
225  226     경상남도   6480000.0   거창군    5470000.0
226  227     경상남도   6480000.0   합천군    5480000.0
227  228     경상남도   6480000.0   창원시    5670000.0
228  229  제주특별자치도   6500000.0   제주시    6510000.0
229  230  제주특별자치도   6500000.0  서귀포시    6520000.0

[230 rows x 5 columns]

In [93]:
seoul_code = list(region_code[region_code['시도명'] == "서울특별시"]['시군구(자치단체)코드'].astype(int).astype(str))
seoul_code

['3000000',
 '3010000',
 '3020000',
 '3030000',
 '3040000',
 '3050000',
 '3060000',
 '3070000',
 '3080000',
 '3090000',
 '3100000',
 '3110000',
 '3120000',
 '3130000',
 '3140000',
 '3150000',
 '3160000',
 '3170000',
 '3180000',
 '3190000',
 '3200000',
 '3210000',
 '3220000',
 '3230000',
 '3240000']

In [94]:
star_bucks_df = star_bucks_df[star_bucks_df['개방자치단체코드'].isin(seoul_code)]

In [95]:
star_bucks_df

,번호,개방서비스명,개방서비스id,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지,Unnamed: 47
3359,3360,휴게음식점,07_24_05_P,3130000,3130000-104-2014-00140,20140624,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,252.76,NaN,NaN,NaN,NaN
34326,34327,휴게음식점,07_24_05_P,3220000,3220000-104-2010-00299,20100826,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,265.23,NaN,NaN,NaN,NaN
34595,34596,휴게음식점,07_24_05_P,3220000,3220000-104-2010-00019,20100129,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,252.77,NaN,NaN,NaN,NaN
35385,35386,휴게음식점,07_24_05_P,3130000,3130000-104-2005-00072,20051220,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,430.91,NaN,NaN,NaN,NaN
35600,35601,휴게음식점,07_24_05_P,3240000,3240000-104-2004-00043,20040621,NaN,03,폐업,02,...,NaN,NaN,NaN,NaN,N,135,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467314,467315,휴게음식점,07_24_05_P,3130000,3130000-104-2017-00384,20171020,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,358.7,NaN,NaN,NaN,NaN
467333,467334,휴게음식점,07_24_05_P,3130000,3130000-104-2016-00422,20161221,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,316.9,NaN,NaN,NaN,NaN
467340,467341,휴게음식점,07_24_05_P,3130000,3130000-104-2018-00012,20180109,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,230.69,NaN,NaN,NaN,NaN
467341,467342,휴게음식점,07_24_05_P,3130000,3130000-104-2018-00011,20180109,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,312.27,NaN,NaN,NaN,NaN
467363,467364,휴게음식점,07_24_05_P,3130000,3130000-104-2016-00394,20161124,NaN,01,영업/정상,01,...,NaN,NaN,NaN,NaN,N,336.35,NaN,NaN,NaN,NaN

In [98]:
star_bucks_df['사업장명'].value_counts()

스타벅스 뚝섬역점            3
스타벅스 국기원사거리점         2
스타벅스커피홍대공원점          1
스타벅스 우장산역점           1
스타벅스 건대스타씨티점         1
                    ..
스타벅스대치역점             1
스타벅스애오개역점            1
스타벅스아크플레이스           1
(주)스타벅스커피코리아 망원역점    1
스타벅스커피 서강대흥역         1
Name: 사업장명, Length: 687, dtype: int64

In [104]:
show_col = ['사업장명', '인허가일자', '인허가취소일자', '폐업일자', '소재지전체주소','도로명전체주소','영업상태명']

In [105]:
# 동일 사업장명에 대한 조사
# 국기원사거리, 뚝섬역점은 폐업한 것이 아닌 이사 또는 층수조정으로 보임 - 폐업상태인 row 제거 필요
star_bucks_df[star_bucks_df['사업장명'].isin(["스타벅스 뚝섬역점","스타벅스 국기원사거리점"])][show_col]

,사업장명,인허가일자,인허가취소일자,폐업일자,소재지전체주소,도로명전체주소,영업상태명
46907,스타벅스 국기원사거리점,20080626,NaN,20140711,서울특별시 강남구 역삼동 827-59번지 지상1층,"서울특별시 강남구 테헤란로8길 32 (역삼동,지상1층)",폐업
184847,스타벅스 뚝섬역점,20171106,NaN,20210303,서울특별시 성동구 성수동1가 14-33 정명빌딩 3층,"서울특별시 성동구 아차산로 42, 3층 (성수동1가)",폐업
184848,스타벅스 뚝섬역점,20171106,NaN,20210303,서울특별시 성동구 성수동1가 14-33 정명빌딩 2층,"서울특별시 성동구 아차산로 42, 2층 (성수동1가)",폐업
424599,스타벅스 뚝섬역점,20171106,NaN,NaN,서울특별시 성동구 성수동1가 14-33 정명빌딩,"서울특별시 성동구 아차산로 42, 1,2,3층 (성수동1가)",영업/정상
436290,스타벅스 국기원사거리점,20190726,NaN,NaN,서울특별시 강남구 역삼동 648-22번지 D.A디에이성형외과,"서울특별시 강남구 테헤란로 125, D.A디에이성형외과 1층,2층 (역삼동)",영업/정상

In [107]:
star_bucks_df.drop([46907,184847,184848], inplace=True)

/Users/mullung/miniforge3/envs/ds2/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [108]:
star_bucks_df['사업장명'].value_counts()

스타벅스커피홍대공원점          1
스타벅스 가양이마트점          1
스타벅스 우장산역점           1
스타벅스 건대스타씨티점         1
스타벅스커피 광나루점          1
                    ..
스타벅스대치역점             1
스타벅스애오개역점            1
스타벅스아크플레이스           1
(주)스타벅스커피코리아 망원역점    1
스타벅스커피 서강대흥역         1
Name: 사업장명, Length: 687, dtype: int64

In [110]:
star_bucks_df[star_bucks_df['폐업일자'].notnull()][show_col]

,사업장명,인허가일자,인허가취소일자,폐업일자,소재지전체주소,도로명전체주소,영업상태명
3359,스타벅스커피홍대공원점,20140624,NaN,20191115,"서울특별시 마포구 서교동 362-1번지 1층일부, 2층","서울특별시 마포구 와우산로 83 (서교동, 1층일부, 2층)",폐업
34326,스타벅스신사가로수길점,20100826,NaN,20151006,서울특별시 강남구 신사동 536-9번지 2층,"서울특별시 강남구 도산대로13길 9 (신사동,2층)",폐업
34595,스타벅스 삼성역사거리점,20100129,NaN,20171130,서울특별시 강남구 대치동 946-18번지 지상1층,"서울특별시 강남구 테헤란로98길 11 (대치동,지상1층)",폐업
35385,스타벅스 홍대정문점,20051220,NaN,20110120,서울특별시 마포구 서교동 360-6번지 1.2.3.4층,NaN,폐업
35600,스타벅스현대천호점,20040621,NaN,20140801,서울특별시 강동구 천호동 455-8번지 현대백화점 지하1층,"서울특별시 강동구 천호대로 1005 (천호동,현대백화점 지하1층)",폐업
...,...,...,...,...,...,...,...
224444,스타벅스커피코리아 명지대점,20150609,NaN,20200518,서울특별시 서대문구 남가좌동 344-1번지 1~3층 전체,"서울특별시 서대문구 거북골로 53, 1~3층 (남가좌동)",폐업
224934,스타벅스 신사2점,20060825,NaN,20141020,서울특별시 서초구 잠원동 28-1번지 2층,"서울특별시 서초구 강남대로 581 (잠원동,2층)",폐업
225057,스타벅스 을지로1가점,20110119,NaN,20151005,"서울특별시 중구 남대문로1가 21번지 (1층, 2층)","서울특별시 중구 남대문로 114-1 (남대문로1가,(1층, 2층))",폐업
225910,스타벅스 명동미래,20100218,NaN,20200924,"서울특별시 중구 명동1가 48-2 ,53-10지상2층","서울특별시 중구 명동7길 8 (명동1가,,53-10지상2층)",폐업
261969,스타벅스홍대입구역사거리R,20180102,NaN,20180703,서울특별시 마포구 서교동 353-5번지 경남관광빌딩,"서울특별시 마포구 양화로 125, 경남관광빌딩 1층 (서교동)",폐업

In [125]:
import numpy as np

In [172]:
cnt_dic = {}
def count_store(row):
    dong = row['소재지전체주소'].split()[2]
    year = int(row['인허가일자'][:4])
    q = (int(row['인허가일자'][4:6]) - 1) // 3 + 1
    
    if row['영업상태명'] == '폐업':
#         print('시작일 : ',row['인허가일자'], year, q, end='\t')
        end_year = int(row['폐업일자'][:4])
        end_q = (int(row['폐업일자'][4:6]) - 1) // 3 + 1
#         print('종료일 : ',row['폐업일자'], end_year, end_q)
    else:
        end_year = 2021
        end_q = 2
#         print('시작일 : ',row['인허가일자'], year, q)
    
    if year < 2014:
        year, q= 2014, 1
    for y in range(year, end_year+1):
        start_q = q if y == year else 1
        e_q = end_q if y == end_year else 4
            
            
        for qq in range(start_q, e_q+1):
            idx = dong+'_'+str(y)+'_'+str(qq)
            if cnt_dic.get(idx):
                cnt_dic[idx][0] += 1
            else:
                cnt_dic[idx] = [1]

In [173]:
for idx, row in star_bucks_df.iterrows():
    count_store(row)

cnt_dic

{'서교동_2014_2': [4],
 '서교동_2014_3': [4],
 '서교동_2014_4': [5],
 '서교동_2015_1': [5],
 '서교동_2015_2': [5],
 '서교동_2015_3': [5],
 '서교동_2015_4': [5],
 '서교동_2016_1': [6],
 '서교동_2016_2': [6],
 '서교동_2016_3': [6],
 '서교동_2016_4': [6],
 '서교동_2017_1': [6],
 '서교동_2017_2': [6],
 '서교동_2017_3': [6],
 '서교동_2017_4': [6],
 '서교동_2018_1': [7],
 '서교동_2018_2': [8],
 '서교동_2018_3': [8],
 '서교동_2018_4': [7],
 '서교동_2019_1': [7],
 '서교동_2019_2': [7],
 '서교동_2019_3': [7],
 '서교동_2019_4': [7],
 '신사동_2014_1': [6],
 '신사동_2014_2': [6],
 '신사동_2014_3': [6],
 '신사동_2014_4': [6],
 '신사동_2015_1': [6],
 '신사동_2015_2': [6],
 '신사동_2015_3': [6],
 '신사동_2015_4': [6],
 '대치동_2014_1': [8],
 '대치동_2014_2': [8],
 '대치동_2014_3': [9],
 '대치동_2014_4': [9],
 '대치동_2015_1': [9],
 '대치동_2015_2': [9],
 '대치동_2015_3': [9],
 '대치동_2015_4': [9],
 '대치동_2016_1': [9],
 '대치동_2016_2': [10],
 '대치동_2016_3': [11],
 '대치동_2016_4': [11],
 '대치동_2017_1': [11],
 '대치동_2017_2': [11],
 '대치동_2017_3': [11],
 '대치동_2017_4': [11],
 '천호동_2014_1': [2],
 '천호동_2014_2': [2],
 '천호동_2014_3': [2],
 '전농동_2014_1': [1],
 '전농동_2014_2': [1],
 '전농동_2014_3': [1],
 '전농동_2014_4': [1],
 '전농동_2015_1': [1],
 '전농동_2015_2': [1],
 '전농동_2015_3': [1],
 '전농동_2015_4': [1],
 '전농동_2016_1': [1],
 '전농동_2016_2': [1],
 '전농동_2016_3': [1],
 '전농동_2016_4': [1],
 '전농동_2017_1': [1],
 '전농동_2017_2': [1],
 '전농동_2017_3': [1],
 '전농동_2017_4': [1],
 '전농동_2018_1': [1],
 '전농동_2018_2': [1],
 '전농동_2018_3': [1],
 '전농동_2018_4': [1],
 '전농동_2019_1': [1],
 '공덕동_2014_1': [1],
 '공덕동_2014_2': [1],
 '공덕동_2014_3': [1],
 '공덕동_2014_4': [1],
 '공덕동_2015_1': [1],
 '공덕동_2015_2': [1],
 '공덕동_2015_3': [1],
 '공덕동_2015_4': [1],
 '공덕동_2016_1': [1],
 '공덕동_2016_2': [1],
 '공덕동_2016_3': [1],
 '공덕동_2016_4': [1],
 '공덕동_2017_1': [1],
 '공덕동_2017_2': [1],
 '공덕동_2017_3': [1],
 '공덕동_2017_4': [1],
 '공덕동_2018_1': [2],
 '공덕동_2018_2': [2],
 '공덕동_2018_3': [2],
 '공덕동_2018_4': [2],
 '공덕동_2019_1': [2],
 '공덕동_2019_2': [2],
 '공덕동_2019_3': [2],
 '삼성동_2014_1': [8],
 '삼성동_2014_2': [7],
 '삼성동_2014_3': [7],
 '삼성동_2014_4': [7],
 '삼성동_2015_1': [7],
 '삼성동_2015_2': [7],
 '삼성동_2015_3': [8],
 '삼성동_2015_4': [8],
 '삼성동_2016_1': [9],
 '삼성동_2016_2': [9],
 '삼성동_2016_3': [9],
 '삼성동_2016_4': [9],
 '삼성동_2017_1': [9],
 '삼성동_2017_2': [10],
 '삼성동_2017_3': [10],
 '삼성동_2017_4': [10],
 '삼성동_2018_1': [12],
 '삼성동_2018_2': [12],
 '삼성동_2018_3': [12],
 '삼성동_2018_4': [12],
 '삼성동_2019_1': [12],
 '삼성동_2019_2': [12],
 '삼성동_2019_3': [12],
 '삼성동_2019_4': [12],
 '삼성동_2020_1': [12],
 '삼성동_2020_2': [14],
 '삼성동_2020_3': [14],
 '삼성동_2020_4': [15],
 '서교동_2014_1': [3],
 '서교동_2020_1': [6],
 '서교동_2020_2': [6],
 '서교동_2020_3': [6],
 '서교동_2020_4': [6],
 '서교동_2021_1': [6],
 '역삼동_2014_1': [17],
 '역삼동_2014_2': [17],
 '역삼동_2014_3': [17],
 '역삼동_2014_4': [17],
 '역삼동_2015_1': [17],
 '역삼동_2015_2': [17],
 '역삼동_2015_3': [17],
 '역삼동_2015_4': [17],
 '역삼동_2016_1': [17],
 '역삼동_2016_2': [17],
 '역삼동_2016_3': [17],
 '역삼동_2016_4': [18],
 '역삼동_2017_1': [18],
 '역삼동_2017_2': [18],
 '역삼동_2017_3': [20],
 '역삼동_2017_4': [20],
 '역삼동_2018_1': [20],
 '역삼동_2018_2': [20],
 '역삼동_2018_3': [20],
 '역삼동_2018_4': [20],
 '역삼동_2019_1': [20],
 '역삼동_2019_2': [21],
 '역삼동_2019_3': [22],
 '역삼동_2019_4': [22],
 '역삼동_2020_1': [22],
 '역삼동_2020_2': [22],
 '역삼동_2020_3': [22],
 '역삼동_2020_4': [24],
 '역삼동_2021_1': [24],
 '역삼동_2021_2': [24],
 '수서동_2014_1': [1],
 '수서동_2014_2': [1],
 '수서동_2014_3': [1],
 '수서동_2014_4': [1],
 '수서동_2015_1': [1],
 '수서동_2015_2': [1],
 '수서동_2015_3': [1],
 '수서동_2015_4': [1],
 '수서동_2016_1': [1],
 '수서동_2016_2': [1],
 '수서동_2016_3': [1],
 '수서동_2016_4': [1],
 '수서동_2017_1': [1],
 '수서동_2017_2': [1],
 '수서동_2017_3': [1],
 '수서동_2017_4': [1],
 '수서동_2018_1': [1],
 '수서동_2018_2': [2],
 '수서동_2018_3': [2],
 '수서동_2018_4': [2],
 '수서동_2019_1': [2],
 '수서동_2019_2': [2],
 '수서동_2019_3': [2],
 '수서동_2019_4': [2],
 '수서동_2020_1': [2],
 '수서동_2020_2': [2],
 '수서동_2020_3': [2],
 '수서동_2020_4': [2],
 '수서동_2021_1': [2],
 '수서동_2021_2': [2],
 '수서동_2021_3': [1],
 '합정동_2014_1': [1],
 '합정동_2014_2': [1],
 '합정동_2014_3': [1],
 '합정동_2014_4': [1],
 '합정동_2015_1': [1],
 '합정동_2015_2': [1],
 '합정동_2015_3': [1],
 '합정동_2015_4': [1],
 '합정동_2016_1': [1],
 '합정동_2016_2': [2],
 '합정동_2016_3': [2],
 '인사동_2014_1': [1],
 '인사동_2014_2': [1],
 '인사동_2014_3': [1],
 '인사동_2014_4': [1],
 '인사동_2015_1': [1],
 '인사동_2015_2': [1],
 '인사동_2015_3': [1],
 '인사동_2015_4': [1],
 '인사동_2016_1': [1],
 '인사동_2016_2': [1],
 '인사동_2016_3': [1],
 '인사동_2016_4': [1],
 '인사동_2017_1': [1],
 '인사동_2017_2': [1],
 '인사동_2017_3': [1],
 '인사동_2017_4': [1],
 '인사동_2018_1': [1],
 '인사동_2018_2': [1],
 '인사동_2018_3': [1],
 '인사동_2018_4': [1],
 '인사동_2019_1': [1],
 '인사동_2019_2': [1],
 '인사동_2019_3': [1],
 '인사동_2019_4': [1],
 '관철동_2014_1': [3],
 '관철동_2014_2': [3],
 '관철동_2014_3': [3],
 '관철동_2014_4': [3],
 '관철동_2015_1': [3],
 '관철동_2015_2': [3],
 '관철동_2015_3': [3],
 '관철동_2015_4': [3],
 '관철동_2016_1': [3],
 '관철동_2016_2': [3],
 '관철동_2016_3': [3],
 '관철동_2016_4': [3],
 '관철동_2017_1': [3],
 '관철동_2017_2': [3],
 '관철동_2017_3': [3],
 '관철동_2017_4': [3],
 '관철동_2018_1': [3],
 '관철동_2018_2': [3],
 '관철동_2018_3': [3],
 '관철동_2018_4': [3],
 '관철동_2019_1': [3],
 '관철동_2019_2': [3],
 '관철동_2019_3': [3],
 '관철동_2019_4': [3],
 '당산동6가_2014_1': [2],
 '당산동6가_2014_2': [2],
 '당산동6가_2014_3': [2],
 '당산동6가_2014_4': [2],
 '당산동6가_2015_1': [2],
 '당산동6가_2015_2': [2],
 '당산동6가_2015_3': [2],
 '당산동6가_2015_4': [2],
 '당산동6가_2016_1': [2],
 '당산동6가_2016_2': [2],
 '당산동6가_2016_3': [2],
 '당산동6가_2016_4': [2],
 '당산동6가_2017_1': [2],
 '당산동6가_2017_2': [2],
 '당산동6가_2017_3': [2],
 '당산동6가_2017_4': [2],
 '당산동6가_2018_1': [2],
 '당산동6가_2018_2': [3],
 '당산동6가_2018_3': [3],
 '당산동6가_2018_4': [3],
 '당산동6가_2019_1': [3],
 '당산동6가_2019_2': [3],
 '당산동6가_2019_3': [3],
 '당산동6가_2019_4': [3],
 '당산동6가_2020_1': [3],
 '당산동6가_2020_2': [3],
 '당산동6가_2020_3': [3],
 '관철동_2020_1': [2],
 '관철동_2020_2': [2],
 '관철동_2020_3': [2],
 '관철동_2020_4': [2],
 '관철동_2021_1': [2],
 '평창동_2014_1': [1],
 '평창동_2014_2': [1],
 '평창동_2014_3': [1],
 '평창동_2014_4': [1],
 '평창동_2015_1': [1],
 '평창동_2015_2': [1],
 '평창동_2015_3': [1],
 '평창동_2015_4': [1],
 '평창동_2016_1': [1],
 '평창동_2016_2': [1],
 '평창동_2016_3': [1],
 '평창동_2016_4': [1],
 '평창동_2017_1': [1],
 '평창동_2017_2': [1],
 '평창동_2017_3': [1],
 '평창동_2017_4': [1],
 '평창동_2018_1': [1],
 '평창동_2018_2': [1],
 '평창동_2018_3': [1],
 '평창동_2018_4': [2],
 '평창동_2019_1': [2],
 '종로2가_2017_4': [2],
 '서초동_2014_1': [17],
 '서초동_2014_2': [18],
 '여의도동_2014_1': [12],
 '여의도동_2014_2': [12],
 '여의도동_2014_3': [12],
 '여의도동_2014_4': [13],
 '여의도동_2015_1': [14],
 '여의도동_2015_2': [14],
 '여의도동_2015_3': [13],
 '여의도동_2015_4': [13],
 '여의도동_2016_1': [14],
 '여의도동_2016_2': [14],
 '여의도동_2016_3': [14],
 '여의도동_2016_4': [16],
 '여의도동_2017_1': [16],
 '여의도동_2017_2': [17],
 '여의도동_2017_3': [17],
 '여의도동_2017_4': [17],
 '여의도동_2018_1': [19],
 '여의도동_2018_2': [19],
 '여의도동_2018_3': [19],
 '여의도동_2018_4': [19],
 '동숭동_2014_1': [3],
 '동숭동_2014_2': [3],
 '동숭동_2014_3': [3],
 '동숭동_2014_4': [3],
 '동숭동_2015_1': [3],
 '동숭동_2015_2': [3],
 '동숭동_2015_3': [3],
 '동숭동_2015_4': [3],
 '동숭동_2016_1': [3],
 '동숭동_2016_2': [3],
 '동숭동_2016_3': [3],
 '동숭동_2016_4': [3],
 '동숭동_2017_1': [3],
 '동숭동_2017_2': [3],
 '동숭동_2017_3': [3],
 '동숭동_2017_4': [3],
 '동숭동_2018_1': [3],
 '동숭동_2018_2': [3],
 '동숭동_2018_3': [3],
 '동숭동_2018_4': [4],
 '방이동_2014_1': [2],
 '방이동_2014_2': [3],
 '방이동_2014_3': [3],
 '방이동_2014_4': [3],
 '방이동_2015_1': [3],
 '방이동_2015_2': [3],
 '공릉동_2014_1': [1],
 '공릉동_2014_2': [1],
 '공릉동_2014_3': [1],
 '공릉동_2014_4': [1],
 '공릉동_2015_1': [1],
 '공릉동_2015_2': [1],
 '공릉동_2015_3': [1],
 '공릉동_2015_4': [1],
 '공릉동_2016_1': [1],
 '공릉동_2016_2': [1],
 '공릉동_2016_3': [1],
 '공릉동_2016_4': [1],
 '공릉동_2017_1': [1],
 '공릉동_2017_2': [1],
 '공릉동_2017_3': [2],
 '공릉동_2017_4': [2],
 '공릉동_2018_1': [2],
 '공릉동_2018_2': [3],
 '공릉동_2018_3': [3],
 '공릉동_2018_4': [3],
 '공릉동_2019_1': [3],
 '공릉동_2019_2': [3],
 '공릉동_2019_3': [3],
 '공릉동_2019_4': [3],
 '공릉동_2020_1': [3],
 '공릉동_2020_2': [3],
 '공릉동_2020_3': [3],
 '천호동_2015_3': [3],
 '천호동_2015_4': [3],
 '천호동_2016_1': [3],
 '천호동_2016_2': [3],
 '천호동_2016_3': [4],
 '천호동_2016_4': [4],
 '천호동_2017_1': [4],
 '천호동_2017_2': [4],
 '천호동_2017_3': [4],
 '천호동_2017_4': [4],
 '천호동_2018_1': [4],
 '천호동_2018_2': [4],
 '천호동_2018_3': [4],
 '천호동_2018_4': [4],
 '성내동_2014_2': [2],
 '성내동_2014_3': [2],
 '성내동_2014_4': [2],
 '성내동_2015_1': [2],
 '성내동_2015_2': [2],
 '성내동_2015_3': [2],
 '성내동_2015_4': [2],
 '성내동_2016_1': [3],
 '성내동_2016_2': [3],
 '성내동_2016_3': [3],
 '성내동_2016_4': [3],
 '성내동_2017_1': [3],
 '성내동_2017_2': [3],
 '성내동_2017_3': [3],
 '성내동_2017_4': [3],
 '성내동_2018_1': [3],
 '성내동_2018_2': [3],
 '성내동_2018_3': [3],
 '성내동_2018_4': [3],
 '성내동_2019_1': [3],
 '성내동_2019_2': [4],
 '성내동_2019_3': [4],
 '성내동_2019_4': [4],
 '성내동_2020_1': [4],
 '성내동_2020_2': [4],
 '성내동_2020_3': [4],
 '성내동_2020_4': [4],
 '성내동_2021_1': [4],
 '성내동_2021_2': [4],
 '성내동_2021_3': [1],
 '화곡동_2014_1': [2],
 '화곡동_2014_2': [2],
 '화곡동_2014_3': [2],
 '화곡동_2014_4': [2],
 '화곡동_2015_1': [3],
 '화곡동_2015_2': [3],
 '화곡동_2015_3': [3],
 '화곡동_2015_4': [3],
 '화곡동_2016_1': [3],
 '화곡동_2016_2': [3],
 '화곡동_2016_3': [3],
 '화곡동_2016_4': [4],
 '화곡동_2017_1': [4],
 '화곡동_2017_2': [4],
 '화곡동_2017_3': [4],
 '신대방동_2014_1': [1],
 '신대방동_2014_2': [1],
 '신대방동_2014_3': [1],
 '신대방동_2014_4': [1],
 '신대방동_2015_1': [1],
 '신대방동_2015_2': [1],
 '신대방동_2015_3': [1],
 '신대방동_2015_4': [1],
 '신대방동_2016_1': [1],
 '신대방동_2016_2': [1],
 '신대방동_2016_3': [1],
 '신대방동_2016_4': [1],
 '신대방동_2017_1': [1],
 '신대방동_2017_2': [1],
 '신대방동_2017_3': [1],
 '신대방동_2017_4': [1],
 '신대방동_2018_1': [1],
 '신대방동_2018_2': [1],
 '신대방동_2018_3': [1],
 '신대방동_2018_4': [1],
 '신대방동_2019_1': [2],
 '길동_2014_1': [1],
 '길동_2014_2': [2],
 '길동_2014_3': [2],
 '길동_2014_4': [2],
 '길동_2015_1': [2],
 '길동_2015_2': [2],
 '길동_2015_3': [2],
 '길동_2015_4': [2],
 '길동_2016_1': [2],
 '길동_2016_2': [2],
 '길동_2016_3': [2],
 '길동_2016_4': [2],
 '길동_2017_1': [2],
 '길동_2017_2': [2],
 '길동_2017_3': [2],
 '길동_2017_4': [2],
 '길동_2018_1': [2],
 '길동_2018_2': [2],
 '길동_2018_3': [2],
 '길동_2018_4': [2],
 '길동_2019_1': [2],
 '길동_2019_2': [2],
 '길동_2019_3': [2],
 '길동_2019_4': [2],
 '길동_2020_1': [2],
 '길동_2020_2': [2],
 '길동_2020_3': [3],
 '양재동_2014_1': [3],
 '양재동_2014_2': [3],
 '양재동_2014_3': [4],
 '명동1가_2014_1': [2],
 '명동1가_2014_2': [2],
 '명동1가_2014_3': [2],
 '명동1가_2014_4': [2],
 '저동1가_2014_1': [1],
 '저동1가_2014_2': [1],
 '저동1가_2014_3': [1],
 '저동1가_2014_4': [1],
 '저동1가_2015_1': [1],
 '저동1가_2015_2': [1],
 '저동1가_2015_3': [1],
 '저동1가_2015_4': [1],
 '저동1가_2016_1': [1],
 '을지로2가_2014_1': [4],
 '을지로2가_2014_2': [5],
 '을지로2가_2014_3': [5],
 '을지로2가_2014_4': [5],
 '을지로2가_2015_1': [4],
 '을지로2가_2015_2': [4],
 '을지로2가_2015_3': [4],
 '을지로2가_2015_4': [4],
 '을지로2가_2016_1': [4],
 '을지로2가_2016_2': [5],
 '방배동_2014_1': [4],
 '방배동_2014_2': [4],
 '방배동_2014_3': [5],
 '방배동_2014_4': [5],
 '방배동_2015_1': [5],
 '방배동_2015_2': [5],
 '방배동_2015_3': [5],
 '방배동_2015_4': [7],
 '방배동_2016_1': [7],
 '방배동_2016_2': [7],
 '방배동_2016_3': [7],
 '방배동_2016_4': [7],
 '방배동_2017_1': [7],
 '방배동_2017_2': [7],
 '방배동_2017_3': [8],
 '방배동_2017_4': [8],
 '방배동_2018_1': [8],
 '방배동_2018_2': [9],
 '방배동_2018_3': [9],
 '서초동_2014_3': [17],
 '서초동_2014_4': [17],
 '서초동_2015_1': [17],
 '서초동_2015_2': [17],
 '서초동_2015_3': [17],
 '서초동_2015_4': [17],
 '서초동_2016_1': [17],
 '서초동_2016_2': [18],
 '서초동_2016_3': [18],
 '서초동_2016_4': [18],
 '서초동_2017_1': [18],
 '서초동_2017_2': [18],
 '서초동_2017_3': [18],
 '서초동_2017_4': [19],
 '서초동_2018_1': [21],
 '여의도동_2019_1': [18],
 '여의도동_2019_2': [19],
 '여의도동_2019_3': [19],
 '여의도동_2019_4': [19],
 '여의도동_2020_1': [18],
 '여의도동_2020_2': [18],
 '반포동_2014_1': [5],
 '반포동_2014_2': [6],
 '반포동_2014_3': [6],
 '반포동_2014_4': [6],
 '반포동_2015_1': [6],
 '반포동_2015_2': [6],
 '반포동_2015_3': [6],
 '반포동_2015_4': [6],
 '반포동_2016_1': [6],
 '반포동_2016_2': [6],
 '반포동_2016_3': [6],
 '반포동_2016_4': [6],
 '반포동_2017_1': [7],
 '명동2가_2014_1': [2],
 '명동2가_2014_2': [2],
 '명동2가_2014_3': [2],
 '명동2가_2014_4': [2],
 '명동2가_2015_1': [2],
 '명동2가_2015_2': [4],
 '명동2가_2015_3': [4],
 '충무로1가_2014_1': [3],
 '충무로1가_2014_2': [3],
 '충무로1가_2014_3': [3],
 '충무로2가_2014_1': [1],
 '충무로2가_2014_2': [1],
 '충무로2가_2014_3': [1],
 '충무로2가_2014_4': [1],
 '충무로2가_2015_1': [1],
 '충무로2가_2015_2': [1],
 '충무로2가_2015_3': [1],
 '충무로1가_2014_4': [2],
 '명동2가_2015_4': [4],
 '명동2가_2016_1': [4],
 '명동2가_2016_2': [4],
 '창천동_2014_1': [7],
 '창천동_2014_2': [7],
 '창천동_2014_3': [7],
 '창천동_2014_4': [7],
 '창천동_2015_1': [7],
 '창천동_2015_2': [7],
 '창천동_2015_3': [7],
 '창천동_2015_4': [7],
 '창천동_2016_1': [7],
 '창천동_2016_2': [7],
 '창천동_2016_3': [7],
 '창천동_2016_4': [7],
 '창천동_2017_1': [7],
 '창천동_2017_2': [7],
 '창천동_2017_3': [6],
 '창천동_2017_4': [7],
 '창천동_2018_1': [7],
 '창천동_2018_2': [7],
 '창천동_2018_3': [7],
 '창천동_2018_4': [7],
 '창천동_2019_1': [7],
 '창천동_2019_2': [7],
 '창천동_2019_3': [7],
 '창천동_2019_4': [7],
 '창천동_2020_1': [6],
 '창천동_2020_2': [6],
 '목동_2014_1': [6],
 '목동_2014_2': [6],
 '목동_2014_3': [6],
 '목동_2014_4': [7],
 '목동_2015_1': [7],
 '목동_2015_2': [7],
 '목동_2015_3': [8],
 '한남동_2014_1': [2],
 '한남동_2014_2': [2],
 '한남동_2014_3': [2],
 '한남동_2014_4': [2],
 '한남동_2015_1': [2],
 '한남동_2015_2': [2],
 '한남동_2015_3': [2],
 '한남동_2015_4': [2],
 '한남동_2016_1': [2],
 '한남동_2016_2': [2],
 '한남동_2016_3': [3],
 '한남동_2016_4': [3],
 '한남동_2017_1': [3],
 '한남동_2017_2': [3],
 '한남동_2017_3': [3],
 '한남동_2017_4': [3],
 '한남동_2018_1': [4],
 '한남동_2018_2': [3],
 '한남동_2018_3': [3],
 '한남동_2018_4': [3],
 '한남동_2019_1': [3],
 '한남동_2019_2': [3],
 '한남동_2019_3': [3],
 '한남동_2019_4': [3],
 '한남동_2020_1': [3],
 '한남동_2020_2': [3],
 '한남동_2020_3': [3],
 '행당동_2014_4': [3],
 '행당동_2015_1': [3],
 '행당동_2015_2': [3],
 '행당동_2015_3': [3],
 '행당동_2015_4': [3],
 '행당동_2016_1': [3],
 '행당동_2016_2': [3],
 '행당동_2016_3': [3],
 '행당동_2016_4': [3],
 '행당동_2017_1': [3],
 '행당동_2017_2': [3],
 '행당동_2017_3': [3],
 '행당동_2017_4': [3],
 '행당동_2018_1': [3],
 '행당동_2018_2': [3],
 '행당동_2018_3': [3],
 '행당동_2018_4': [3],
 '행당동_2019_1': [3],
 '행당동_2019_2': [3],
 '행당동_2019_3': [3],
 '행당동_2019_4': [3],
 '행당동_2020_1': [3],
 '행당동_2020_2': [3],
 '행당동_2020_3': [3],
 '행당동_2020_4': [3],
 '행당동_2021_1': [3],
 '이태원동_2014_1': [2],
 '이태원동_2014_2': [2],
 '이태원동_2014_3': [2],
 '이태원동_2014_4': [1],
 '이태원동_2015_1': [1],
 '이태원동_2015_2': [1],
 '이태원동_2015_3': [1],
 '이태원동_2015_4': [1],
 '이태원동_2016_1': [1],
 '이태원동_2016_2': [1],
 '이태원동_2016_3': [1],
 '이태원동_2016_4': [1],
 '이태원동_2017_1': [1],
 '이태원동_2017_2': [1],
 '이태원동_2017_3': [1],
 '이태원동_2017_4': [1],
 '이태원동_2018_1': [1],
 '이태원동_2018_2': [1],
 '목동_2015_4': [7],
 '목동_2016_1': [7],
 '목동_2016_2': [7],
 '목동_2016_3': [8],
 '목동_2016_4': [8],
 '목동_2017_1': [8],
 '목동_2017_2': [8],
 '목동_2017_3': [8],
 '목동_2017_4': [8],
 '목동_2018_1': [8],
 '목동_2018_2': [8],
 '목동_2018_3': [9],
 '목동_2018_4': [10],
 '목동_2019_1': [10],
 '목동_2019_2': [10],
 '목동_2019_3': [10],
 '목동_2019_4': [11],
 '목동_2020_1': [11],
 '목동_2020_2': [11],
 '목동_2020_3': [12],
 '안암동5가_2014_1': [3],
 '안암동5가_2014_2': [3],
 '안암동5가_2014_3': [3],
 '안암동5가_2014_4': [3],
 '안암동5가_2015_1': [3],
 '안암동5가_2015_2': [3],
 '안암동5가_2015_3': [3],
 '안암동5가_2015_4': [3],
 '안암동5가_2016_1': [3],
 '안암동5가_2016_2': [3],
 '안암동5가_2016_3': [3],
 '안암동5가_2016_4': [3],
 '안암동5가_2017_1': [3],
 '안암동5가_2017_2': [3],
 '안암동5가_2017_3': [3],
 '안암동5가_2017_4': [3],
 '안암동5가_2018_1': [3],
 '안암동5가_2018_2': [3],
 '안암동5가_2018_3': [3],
 '안암동5가_2018_4': [3],
 '안암동5가_2019_1': [3],
 '안암동5가_2019_2': [3],
 '안국동_2014_1': [1],
 '안국동_2014_2': [1],
 '안국동_2014_3': [1],
 '대조동_2014_1': [2],
 '대조동_2014_2': [2],
 '대조동_2014_3': [2],
 '대조동_2014_4': [2],
 '대조동_2015_1': [2],
 '대조동_2015_2': [2],
 '대조동_2015_3': [2],
 '대조동_2015_4': [2],
 '대조동_2016_1': [2],
 '대조동_2016_2': [2],
 '대조동_2016_3': [2],
 '대조동_2016_4': [2],
 '대조동_2017_1': [2],
 '대조동_2017_2': [2],
 '대조동_2017_3': [2],
 '대조동_2017_4': [2],
 '대조동_2018_1': [2],
 '대조동_2018_2': [2],
 '대조동_2018_3': [2],
 '대조동_2018_4': [2],
 '대조동_2019_1': [2],
 '대조동_2019_2': [3],
 '회현동2가_2014_1': [1],
 '회현동2가_2014_2': [1],
 '회현동2가_2014_3': [1],
 '회현동2가_2014_4': [1],
 '회현동2가_2015_1': [1],
 '회현동2가_2015_2': [1],
 '회현동2가_2015_3': [1],
 '회현동2가_2015_4': [1],
 '회현동2가_2016_1': [1],
 '회현동2가_2016_2': [1],
 '회현동2가_2016_3': [1],
 '회현동2가_2016_4': [1],
 '회현동2가_2017_1': [1],
 '회현동2가_2017_2': [1],
 '회현동2가_2017_3': [1],
 '회현동2가_2017_4': [1],
 '회현동2가_2018_1': [1],
 '회현동2가_2018_2': [1],
 '회현동2가_2018_3': [1],
 '회현동2가_2018_4': [1],
 '회현동2가_2019_1': [1],
 '회현동2가_2019_2': [1],
 '회현동2가_2019_3': [1],
 '회현동2가_2019_4': [1],
 '회현동2가_2020_1': [1],
 '회현동2가_2020_2': [1],
 '회현동2가_2020_3': [1],
 '회현동2가_2020_4': [1],
 '회현동2가_2021_1': [1],
 '남가좌동_2015_2': [1],
 '남가좌동_2015_3': [1],
 '남가좌동_2015_4': [1],
 '남가좌동_2016_1': [1],
 '남가좌동_2016_2': [1],
 '남가좌동_2016_3': [1],
 '남가좌동_2016_4': [1],
 '남가좌동_2017_1': [1],
 '남가좌동_2017_2': [1],
 '남가좌동_2017_3': [1],
 '남가좌동_2017_4': [1],
 '남가좌동_2018_1': [1],
 '남가좌동_2018_2': [1],
 '남가좌동_2018_3': [1],
 '남가좌동_2018_4': [1],
 '남가좌동_2019_1': [1],
 '남가좌동_2019_2': [2],
 '남가좌동_2019_3': [2],
 '남가좌동_2019_4': [2],
 '남가좌동_2020_1': [2],
 '남가좌동_2020_2': [3],
 '잠원동_2014_1': [3],
 '잠원동_2014_2': [3],
 '잠원동_2014_3': [4],
 '잠원동_2014_4': [4],
 '남대문로1가_2014_1': [1],
 '남대문로1가_2014_2': [1],
 '남대문로1가_2014_3': [1],
 '남대문로1가_2014_4': [1],
 '남대문로1가_2015_1': [1],
 '남대문로1가_2015_2': [1],
 '남대문로1가_2015_3': [1],
 '남대문로1가_2015_4': [1],
 '명동1가_2015_1': [1],
 '명동1가_2015_2': [1],
 '명동1가_2015_3': [1],
 '명동1가_2015_4': [1],
 '명동1가_2016_1': [1],
 '명동1가_2016_2': [1],
 '명동1가_2016_3': [1],
 '명동1가_2016_4': [1],
 '명동1가_2017_1': [1],
 '명동1가_2017_2': [1],
 '명동1가_2017_3': [1],
 '명동1가_2017_4': [1],
 '명동1가_2018_1': [1],
 '명동1가_2018_2': [1],
 '명동1가_2018_3': [1],
 '명동1가_2018_4': [2],
 '명동1가_2019_1': [2],
 '명동1가_2019_2': [2],
 '명동1가_2019_3': [2],
 '명동1가_2019_4': [2],
 '명동1가_2020_1': [2],
 '명동1가_2020_2': [2],
 '명동1가_2020_3': [2],
 '창천동_2021_1': [6],
 '창천동_2021_2': [6],
 '대치동_2021_1': [15],
 '대치동_2021_2': [15],
 '중화동_2020_4': [1],
 '중화동_2021_1': [1],
 '중화동_2021_2': [1],
 '한강로3가_2020_4': [2],
 '한강로3가_2021_1': [2],
 '한강로3가_2021_2': [2],
 '동교동_2021_1': [4],
 '동교동_2021_2': [4],
 '고덕동_2021_1': [1],
 '고덕동_2021_2': [1],
 '대치동_2020_4': [14],
 '사당동_2018_4': [2],
 '사당동_2019_1': [2],
 '사당동_2019_2': [2],
 '사당동_2019_3': [3],
 '사당동_2019_4': [3],
 '사당동_2020_1': [3],
 '사당동_2020_2': [3],
 '사당동_2020_3': [3],
 '사당동_2020_4': [3],
 '사당동_2021_1': [3],
 '사당동_2021_2': [3],
 '신천동_2018_4': [4],
 '신천동_2019_1': [4],
 '신천동_2019_2': [4],
 '신천동_2019_3': [4],
 '신천동_2019_4': [4],
 '신천동_2020_1': [4],
 '신천동_2020_2': [4],
 '신천동_2020_3': [4],
 '신천동_2020_4': [4],
 '신천동_2021_1': [4],
 '신천동_2021_2': [4],
 '명동1가_2020_4': [1],
 '명동1가_2021_1': [1],
 '명동1가_2021_2': [1],
 '명일동_2018_4': [2],
 '명일동_2019_1': [2],
 '명일동_2019_2': [2],
 '명일동_2019_3': [2],
 '명일동_2019_4': [2],
 '명일동_2020_1': [2],
 '명일동_2020_2': [3],
 '명일동_2020_3': [3],
 '명일동_2020_4': [3],
 '명일동_2021_1': [3],
 '명일동_2021_2': [3],
 '동숭동_2019_1': [3],
 '동숭동_2019_2': [3],
 '동숭동_2019_3': [3],
 '동숭동_2019_4': [3],
 '동숭동_2020_1': [3],
 '동숭동_2020_2': [3],
 '동숭동_2020_3': [3],
 '동숭동_2020_4': [3],
 '동숭동_2021_1': [3],
 '동숭동_2021_2': [3],
 '상암동_2015_1': [3],
 '상암동_2015_2': [3],
 '상암동_2015_3': [3],
 '상암동_2015_4': [3],
 '상암동_2016_1': [3],
 '상암동_2016_2': [4],
 '상암동_2016_3': [4],
 '상암동_2016_4': [4],
 '상암동_2017_1': [4],
 '상암동_2017_2': [4],
 '상암동_2017_3': [4],
 '상암동_2017_4': [4],
 '상암동_2018_1': [4],
 '상암동_2018_2': [4],
 '상암동_2018_3': [4],
 '상암동_2018_4': [4],
 '상암동_2019_1': [4],
 '상암동_2019_2': [5],
 '상암동_2019_3': [5],
 '상암동_2019_4': [5],
 '상암동_2020_1': [5],
 '상암동_2020_2': [5],
 '상암동_2020_3': [5],
 '상암동_2020_4': [5],
 '상암동_2021_1': [5],
 '상암동_2021_2': [5],
 '동교동_2014_1': [2],
 '동교동_2014_2': [2],
 '동교동_2014_3': [2],
 '동교동_2014_4': [2],
 '동교동_2015_1': [2],
 '동교동_2015_2': [2],
 '동교동_2015_3': [2],
 '동교동_2015_4': [2],
 '동교동_2016_1': [2],
 '동교동_2016_2': [2],
 '동교동_2016_3': [2],
 '동교동_2016_4': [2],
 '동교동_2017_1': [2],
 '동교동_2017_2': [2],
 '동교동_2017_3': [2],
 '동교동_2017_4': [3],
 '동교동_2018_1': [3],
 '동교동_2018_2': [3],
 '동교동_2018_3': [3],
 '동교동_2018_4': [3],
 '동교동_2019_1': [3],
 '동교동_2019_2': [3],
 '동교동_2019_3': [3],
 '동교동_2019_4': [3],
 '동교동_2020_1': [3],
 '동교동_2020_2': [3],
 '동교동_2020_3': [3],
 '동교동_2020_4': [3],
 '노고산동_2016_2': [1],
 '노고산동_2016_3': [1],
 '노고산동_2016_4': [1],
 '노고산동_2017_1': [1],
 '노고산동_2017_2': [1],
 '노고산동_2017_3': [1],
 '노고산동_2017_4': [1],
 '노고산동_2018_1': [1],
 '노고산동_2018_2': [1],
 '노고산동_2018_3': [1],
 '노고산동_2018_4': [1],
 '노고산동_2019_1': [1],
 '노고산동_2019_2': [1],
 '노고산동_2019_3': [1],
 '노고산동_2019_4': [1],
 '노고산동_2020_1': [1],
 '노고산동_2020_2': [1],
 '노고산동_2020_3': [1],
 '노고산동_2020_4': [1],
 '노고산동_2021_1': [1],
 '노고산동_2021_2': [1],
 '신수동_2014_2': [1],
 '신수동_2014_3': [1],

In [177]:
star_bucks_cnt_df = pd.DataFrame(cnt_dic).transpose()
star_bucks_cnt_df.columns=['스타벅스매장수']
star_bucks_cnt_df

            스타벅스매장수
서교동_2014_2        4
서교동_2014_3        4
서교동_2014_4        5
서교동_2015_1        5
서교동_2015_2        5
...             ...
대흥동_2020_2        1
대흥동_2020_3        1
대흥동_2020_4        1
대흥동_2021_1        1
대흥동_2021_2        1

[5298 rows x 1 columns]

In [178]:
star_bucks_cnt_df.to_csv('star_bucks_cnt_df.csv')